# Chapter 12 (Urinary and Male Reproductive) terms from the Acquiring Medical Language quick-reference word list.
# Only the WORDS come from the book. Definitions, splits and pronunciations are written by MedDecode (drafts for review).
PARTS12 = {
 'en':('en-','prefix','in, within','en','General',True,None),
 'circum':('circum-','prefix','around','SER-kum','General',True,None),
 're':('re-','prefix','back, again','ree','General',True,None),
 'ultra':('ultra-','prefix','beyond, excess','UL-truh','General',True,None),
 'balan':('balan/o','root','glans penis (tip of the penis)','BAL-uh-noh','Male reproductive',True,None),
 'epididym':('epididym/o','root','epididymis (coiled tube on the testis where sperm mature)','ep-ih-DID-ih-moh','Male reproductive',True,None),
 'glomerul':('glomerul/o','root','glomerulus (tiny filter in the kidney)','gloh-MER-yoo-loh','Urinary',True,None),
 'meat':('meat/o','root','meatus (opening of the urethra)','mee-AY-toh','Urinary',True,None),
 'ren':('ren/o','root','kidney','REE-noh','Urinary',True,'kidney'),
 'sperm':('sperm/o','root','sperm','SPER-moh','Male reproductive',True,'sperm'),
 'spermat':('spermat/o','root','sperm','sper-MAT-oh','Male reproductive',False,'sperm'),
 'test':('test/o','root','testis, testicle','TES-toh','Male reproductive',True,'testis'),
 'orchi':('orchi/o','root','testis, testicle','OR-kee-oh','Male reproductive',False,'testis'),
 'orchid':('orchid/o','root','testis, testicle','OR-kih-doh','Male reproductive',False,'testis'),
 'ureter':('ureter/o','root','ureter (tube from kidney to bladder)','yoo-REE-ter-oh','Urinary',True,None),
 'urethr':('urethr/o','root','urethra (tube from bladder to outside)','yoo-REE-throh','Urinary',True,None),
 'vesic':('vesic/o','root','urinary bladder','VES-ih-koh','Urinary',True,'bladder'),
 'vesicul':('vesicul/o','root','seminal vesicle','veh-SIK-yoo-loh','Male reproductive',True,None),
 'azot':('azot/o','root','nitrogen, urea','AZ-oh-toh','General',True,None),
 'albumin':('albumin/o','root','albumin (a blood protein)','al-BYOO-mih-noh','General',True,None),
 'kal':('kal/i','root','potassium','KAY-lih','General',True,None),
 'natr':('natr/o','root','sodium','NAY-troh','General',True,None),
 'ket':('ket/o','root','ketones','KEE-toh','General',True,'ketone'),
 'keton':('keton/o','root','ketones','KEE-toh-noh','General',False,'ketone'),
 'py':('py/o','root','pus','PY-oh','General',True,None),
 'crypt':('crypt/o','root','hidden','KRIP-toh','General',True,None),
 'glucos':('glucos/o','root','glucose, sugar','GLOO-koh-soh','General',False,None),
 'glycos':('glycos/o','root','glucose, sugar','GLY-koh-soh','General',False,None),
 'gon':('gon/o','root','seed; reproductive organs','GON-oh','Male reproductive',True,None),
 'lapar':('lapar/o','root','abdomen','LAP-uh-roh','General',True,None),
 'son':('son/o','root','sound','SON-oh','General',True,None),
 'dips':('dips/o','root','thirst','DIP-soh','General',True,'thirst'),
 'noct':('noct/i','root','night','NOK-tih','General',True,None),
 'zo':('zo/o','root','life, living animal','ZOH-oh','General',False,None),
 'cis':('cis/o','root','to cut','SIZ-oh','General',False,None),
 'sect':('sect/o','root','to cut','SEK-toh','General',False,None),
 'semin':('semin/i','root','semen','SEM-ih-nih','Male reproductive',True,None),
 'ile':('ile/o','root','ileum (last part of the small intestine)','IL-ee-oh','Digestive',True,None),
 'varic':('varic/o','root','swollen, twisted vein','VAIR-ih-koh','Cardiovascular',True,None),
 'xanth':('xanth/o','root','yellow','ZAN-thoh','General',True,None),
 'cele':('-cele','suffix','hernia, swelling','seel','General',True,None),
 'dynia':('-dynia','suffix','pain','DIN-ee-uh','General',True,'pain'),
 'pexy':('-pexy','suffix','surgical fixation','PEK-see','General',True,None),
 'ptosis':('-ptosis','suffix','drooping, falling','TOH-sis','General',True,None),
 'rrhexis':('-rrhexis','suffix','rupture','REK-sis','General',True,None),
 'rrhaphy':('-rrhaphy','suffix','suture, stitching','RAF-ee','General',True,None),
 'spasm':('-spasm','suffix','sudden involuntary tightening','SPAZ-um','General',True,None),
 'stenosis':('-stenosis','suffix','narrowing','steh-NOH-sis','General',True,None),
 'ectasia':('-ectasia','suffix','widening, dilation','ek-TAY-zhuh','General',True,'dilation'),
 'ectasis':('-ectasis','suffix','widening, dilation','EK-tuh-sis','General',False,'dilation'),
 'tripsy':('-tripsy','suffix','crushing','TRIP-see','General',True,None),
 'poiesis':('-poiesis','suffix','formation, production','poy-EE-sis','General',True,'formation'),
 'genesis':('-genesis','suffix','creation, formation','JEN-eh-sis','General',True,'formation'),
 'genic':('-genic','suffix','producing, causing','JEN-ik','General',True,None),
 'cide':('-cide','suffix','killing, agent that kills','side','General',True,None),
 'lytic':('-lytic','suffix','destroying, breaking down','LIT-ik','General',False,None),
 'esis':('-esis','suffix','condition, action','EE-sis','General',False,None),
 'etic':('-etic','suffix','pertaining to','ET-ik','General',False,None),
 'logist':('-logist','suffix','specialist in the study of','LOJ-ist','General',True,None),
 'anastomosis':('-anastomosis','suffix','surgical connection between two structures','uh-nas-tuh-MOH-sis','General',True,'connect'),
 'stomosis':('-stomosis','suffix','surgical connection','stuh-MOH-sis','General',False,'connect'),
 'ion':('-ion','suffix','action, process','yun','General',False,None),
 'in':('-in','suffix','substance','in','General',False,None),
 'toxin':('-toxin','suffix','poison','TOK-sin','General',True,None),
 'trophy':('-trophy','suffix','growth, development','truh-fee','General',True,None),
}
# (word, split, definition, pronunciation, kind, level). Split tokens: part id, or letters=partid; 'o'/'i' alone = combining vowel.
T12 = [
 ('albuminuria','albumin|uria','albumin (a protein) in the urine, a sign of kidney damage','al-byoo-mih-NOO-ree-uh','sign','medium'),
 ('anorchidism','an=a|orchid|ism','absence of one or both testes at birth','an-OR-kih-diz-um','condition','hard'),
 ('aspermia','a|sperm|ia','absence of sperm or semen','ay-SPER-mee-uh','condition','medium'),
 ('azoospermia','a|zo|o|sperm|ia','no sperm in the semen','ay-zoh-oh-SPER-mee-uh','condition','hard'),
 ('azotemia','azot|emia','too much nitrogen waste (urea) in the blood','az-oh-TEE-mee-uh','condition','medium'),
 ('azotorrhea','azot|o|rrhea','too much nitrogen waste in the stool or urine','az-oh-toh-REE-uh','sign','medium'),
 ('azoturia','azot|uria','too much nitrogen waste (urea) in the urine','az-oh-TOO-ree-uh','sign','medium'),
 ('balanitis','balan|itis','inflammation of the tip of the penis','bal-uh-NY-tis','condition','easy'),
 ('balanoplasty','balan|o|plasty','surgical repair of the tip of the penis','BAL-uh-noh-plas-tee','procedure','easy'),
 ('balanorrhea','balan|o|rrhea','discharge from the tip of the penis','bal-uh-noh-REE-uh','sign','easy'),
 ('circumcision','circum|cis|ion','surgical removal of the foreskin of the penis','ser-kum-SIZH-un','procedure','medium'),
 ('cryptorchidism','crypt|orchid|ism','a testis that has not moved down into the scrotum (undescended testis)','kript-OR-kih-diz-um','condition','hard'),
 ('cystalgia','cyst|algia','pain in the urinary bladder','sis-TAL-juh','symptom','easy'),
 ('cystectomy','cyst|ectomy','surgical removal of the urinary bladder','sis-TEK-tuh-mee','procedure','easy'),
 ('cystocele','cyst|o|cele','the bladder bulging into the wall of the vagina (bladder hernia)','SIS-toh-seel','condition','easy'),
 ('cystodynia','cyst|o|dynia','pain in the urinary bladder','sis-toh-DIN-ee-uh','symptom','easy'),
 ('cystogram','cyst|o|gram','an x-ray picture of the urinary bladder','SIS-toh-gram','test','easy'),
 ('cystography','cyst|o|graphy','the process of taking x-ray pictures of the urinary bladder','sis-TOG-ruh-fee','test','easy'),
 ('cystolith','cyst|o|lith','a stone in the urinary bladder','SIS-toh-lith','condition','easy'),
 ('cystolithectomy','cyst|o|lith|ectomy','surgical removal of a bladder stone','sis-toh-lih-THEK-tuh-mee','procedure','hard'),
 ('cystoma','cyst|oma','a tumor of the urinary bladder','sis-TOH-muh','condition','easy'),
 ('cystoplegia','cyst|o|plegia','paralysis of the urinary bladder','sis-toh-PLEE-juh','condition','easy'),
 ('cystoptosis','cyst|o|ptosis','drooping of the urinary bladder out of its normal position','sis-top-TOH-sis','condition','easy'),
 ('cystorrhexis','cyst|o|rrhexis','rupture of the urinary bladder','sis-toh-REK-sis','condition','easy'),
 ('cystospasm','cyst|o|spasm','a sudden, involuntary tightening of the bladder','SIS-toh-spaz-um','symptom','easy'),
 ('cystostomy','cyst|ostomy','a new surgical opening into the urinary bladder','sis-TOS-tuh-mee','procedure','easy'),
 ('cystoureteritis','cyst|o|ureter|itis','inflammation of the urinary bladder and a ureter','sis-toh-yoo-ree-ter-EYE-tis','condition','hard'),
 ('cystourethrocele','cyst|o|urethr|o|cele','the bladder and urethra bulging into the wall of the vagina','sis-toh-yoo-REE-throh-seel','condition','hard'),
 ('dipsogenic','dips|o|genic','causing thirst','dip-soh-JEN-ik','descriptive word','medium'),
 ('diuresis','di=dia|ur|esis','producing a large amount of urine','dy-yoo-REE-sis','sign','medium'),
 ('diuretic','di=dia|ur|etic','a medicine that makes the kidneys produce more urine (a "water pill")','dy-yoo-RET-ik','medication','medium'),
 ('enuresis','en|ur|esis','involuntary release of urine, especially bedwetting','en-yoo-REE-sis','symptom','medium'),
 ('epididymectomy','epididym|ectomy','surgical removal of the epididymis','ep-ih-did-ih-MEK-tuh-mee','procedure','easy'),
 ('epididymitis','epididym|itis','inflammation of the epididymis','ep-ih-did-ih-MY-tis','condition','easy'),
 ('epididymotomy','epididym|otomy','an incision into the epididymis','ep-ih-did-ih-MOT-uh-mee','procedure','easy'),
 ('glomerulonephritis','glomerul|o|nephr|itis','inflammation of the kidney\'s filters (glomeruli)','gloh-mer-yoo-loh-neh-FRY-tis','condition','hard'),
 ('glomerulopathy','glomerul|o|pathy','disease of the kidney\'s filters (glomeruli)','gloh-mer-yoo-LOP-uh-thee','condition','medium'),
 ('glomerulosclerosis','glomerul|o|scler|osis','scarring and hardening of the kidney\'s filters (glomeruli)','gloh-mer-yoo-loh-skleh-ROH-sis','condition','hard'),
 ('glucosuria','glucos|uria','glucose (sugar) in the urine','gloo-koh-SOO-ree-uh','sign','medium'),
 ('glycosuria','glycos|uria','glucose (sugar) in the urine','gly-koh-SOO-ree-uh','sign','medium'),
 ('gonorrhea','gon|o|rrhea','a sexually transmitted bacterial infection that often causes discharge','gon-oh-REE-uh','condition','medium'),
 ('heminephrectomy','hemi|nephr|ectomy','surgical removal of part (half) of a kidney','hem-ee-neh-FREK-tuh-mee','procedure','medium'),
 ('heminephroureterectomy','hemi|nephr|o|ureter|ectomy','surgical removal of part of a kidney and its ureter','hem-ee-nef-roh-yoo-ree-ter-EK-tuh-mee','procedure','hard'),
 ('hemodialysis','hem|o|dia|lysis','using a machine to filter wastes from the blood when the kidneys fail','hee-moh-dy-AL-ih-sis','procedure','hard'),
 ('hydrocele','hydr|o|cele','a collection of fluid around a testis that causes swelling','HY-droh-seel','condition','easy'),
 ('hydrocelectomy','hydr|o|cel=cele|ectomy','surgical removal of a hydrocele','hy-droh-see-LEK-tuh-mee','procedure','hard'),
 ('hydronephrosis','hydr|o|nephr|osis','swelling of a kidney from urine that cannot drain','hy-droh-neh-FROH-sis','condition','hard'),
 ('hyperkalemia','hyper|kal|emia','too much potassium in the blood','hy-per-kuh-LEE-mee-uh','condition','medium'),
 ('hypernephroma','hyper|nephr|oma','an older name for renal cell carcinoma, the most common kidney cancer','hy-per-neh-FROH-muh','condition','medium'),
 ('hyponatremia','hypo|natr|emia','too little sodium in the blood','hy-poh-nuh-TREE-mee-uh','condition','medium'),
 ('ketolysis','ket|o|lysis','the breakdown of ketones','kee-TOL-ih-sis','process','medium'),
 ('ketonuria','keton|uria','ketones in the urine, often from uncontrolled diabetes or starvation','kee-toh-NOO-ree-uh','sign','medium'),
 ('laparonephrectomy','lapar|o|nephr|ectomy','removal of a kidney through small cuts in the abdomen','lap-uh-roh-neh-FREK-tuh-mee','procedure','hard'),
 ('lithectomy','lith|ectomy','surgical removal of a stone','lih-THEK-tuh-mee','procedure','easy'),
 ('lithocystotomy','lith|o|cyst|otomy','an incision into the bladder to remove a stone','lith-oh-sis-TOT-uh-mee','procedure','hard'),
 ('lithonephritis','lith|o|nephr|itis','inflammation of a kidney caused by stones','lith-oh-neh-FRY-tis','condition','hard'),
 ('lithonephrotomy','lith|o|nephr|otomy','an incision into a kidney to remove a stone','lith-oh-neh-FROT-uh-mee','procedure','hard'),
 ('lithotripsy','lith|o|tripsy','crushing a stone into small pieces that can pass in the urine','LITH-oh-trip-see','procedure','easy'),
 ('meatoplasty','meat|o|plasty','surgical repair of the urinary opening (meatus)','mee-AY-toh-plas-tee','procedure','easy'),
 ('meatorrhaphy','meat|o|rrhaphy','suturing of the urinary opening (meatus)','mee-uh-TOR-uh-fee','procedure','easy'),
 ('meatoscope','meat|o|scope','an instrument for looking at the urinary opening (meatus)','mee-AY-toh-skohp','instrument','easy'),
 ('meatoscopy','meat|o|scopy','examination of the urinary opening (meatus) with a scope','mee-uh-TOS-kuh-pee','test','easy'),
 ('meatotomy','meat|otomy','an incision to widen the urinary opening (meatus)','mee-uh-TOT-uh-mee','procedure','easy'),
 ('nephralgia','nephr|algia','kidney pain','neh-FRAL-juh','symptom','easy'),
 ('nephrocele','nephr|o|cele','a hernia or displacement of a kidney','NEF-roh-seel','condition','easy'),
 ('nephrocystanastomosis','nephr|o|cyst|anastomosis','surgically connecting a kidney to the urinary bladder','nef-roh-sist-uh-nas-tuh-MOH-sis','procedure','hard'),
 ('nephrogram','nephr|o|gram','an x-ray picture of a kidney','NEF-roh-gram','test','easy'),
 ('nephrography','nephr|o|graphy','the process of taking x-ray pictures of a kidney','neh-FROG-ruh-fee','test','easy'),
 ('nephrohypertrophy','nephr|o|hyper|trophy','enlargement of a kidney from overgrowth','nef-roh-hy-PER-truh-fee','condition','hard'),
 ('nephrolithotomy','nephr|o|lith|otomy','an incision into a kidney to remove a stone','nef-roh-lih-THOT-uh-mee','procedure','hard'),
 ('nephrologist','nephr|o|logist','a doctor who specializes in kidney disease','neh-FROL-uh-jist','specialist','easy'),
 ('nephroma','nephr|oma','a tumor of the kidney','neh-FROH-muh','condition','easy'),
 ('nephromalacia','nephr|o|malacia','softening of a kidney','nef-roh-muh-LAY-shuh','condition','easy'),
 ('nephromegaly','nephr|o|megaly','enlargement of a kidney','nef-roh-MEG-uh-lee','sign','easy'),
 ('nephropathy','nephr|o|pathy','any disease of the kidney','neh-FROP-uh-thee','condition','easy'),
 ('nephropexy','nephr|o|pexy','surgically fixing a loose kidney in place','NEF-roh-pek-see','procedure','easy'),
 ('nephroptosis','nephr|o|ptosis','a kidney that has dropped out of its normal position','nef-rop-TOH-sis','condition','easy'),
 ('nephrorrhaphy','nephr|o|rrhaphy','suturing of a kidney','neh-FROR-uh-fee','procedure','easy'),
 ('nephrosclerosis','nephr|o|scler|osis','hardening of the kidney\'s blood vessels and tissue','nef-roh-skleh-ROH-sis','condition','hard'),
 ('nephroscopy','nephr|o|scopy','examination inside a kidney with a scope','neh-FROS-kuh-pee','test','easy'),
 ('nephrosis','nephr|osis','a kidney disease in which protein leaks into the urine','neh-FROH-sis','condition','easy'),
 ('nephrosonography','nephr|o|son|o|graphy','an ultrasound (sound-wave) image of a kidney','nef-roh-soh-NOG-ruh-fee','test','hard'),
 ('nephrostomy','nephr|ostomy','a new opening into a kidney so urine can drain through a tube','neh-FROS-tuh-mee','procedure','easy'),
 ('nephrotomy','nephr|otomy','an incision into a kidney','neh-FROT-uh-mee','procedure','easy'),
 ('nephrotoxin','nephr|o|toxin','a substance that damages the kidneys','nef-roh-TOK-sin','substance','medium'),
 ('nephroureterectomy','nephr|o|ureter|ectomy','surgical removal of a kidney and its ureter','nef-roh-yoo-ree-ter-EK-tuh-mee','procedure','hard'),
 ('nocturia','noct|uria','waking at night to urinate','nok-TOO-ree-uh','symptom','medium'),
 ('oligospermia','olig|o|sperm|ia','a low number of sperm in the semen','ol-ih-goh-SPER-mee-uh','condition','medium'),
 ('orchialgia','orchi|algia','pain in a testis','or-kee-AL-juh','symptom','easy'),
 ('orchidectomy','orchid|ectomy','surgical removal of a testis','or-kih-DEK-tuh-mee','procedure','easy'),
 ('orchiditis','orchid|itis','inflammation of a testis','or-kih-DY-tis','condition','easy'),
 ('orchidopexy','orchid|o|pexy','surgically fixing a testis in the scrotum','OR-kih-doh-pek-see','procedure','easy'),
 ('orchidoptosis','orchid|o|ptosis','a testis that hangs lower than normal','or-kih-dop-TOH-sis','condition','easy'),
 ('orchidotomy','orchid|otomy','an incision into a testis','or-kih-DOT-uh-mee','procedure','easy'),
 ('orchiectomy','orchi|ectomy','surgical removal of a testis','or-kee-EK-tuh-mee','procedure','easy'),
 ('orchiepididymitis','orchi|epididym|itis','inflammation of a testis and its epididymis','or-kee-ep-ih-did-ih-MY-tis','condition','hard'),
 ('orchiodynia','orchi|o|dynia','pain in a testis','or-kee-oh-DIN-ee-uh','symptom','easy'),
 ('orchiopathy','orchi|o|pathy','any disease of a testis','or-kee-OP-uh-thee','condition','easy'),
 ('orchiopexy','orchi|o|pexy','surgically fixing a testis in the scrotum','OR-kee-oh-pek-see','procedure','easy'),
 ('orchioplasty','orchi|o|plasty','surgical repair of a testis','OR-kee-oh-plas-tee','procedure','easy'),
 ('prostatocystitis','prostat|o|cyst|itis','inflammation of the prostate and urinary bladder','pros-tuh-toh-sis-TY-tis','condition','hard'),
 ('prostatolith','prostat|o|lith','a stone in the prostate','pros-TAT-oh-lith','condition','easy'),
 ('prostatolithotomy','prostat|o|lith|otomy','an incision into the prostate to remove a stone','pros-tuh-toh-lih-THOT-uh-mee','procedure','hard'),
 ('prostatomegaly','prostat|o|megaly','enlargement of the prostate','pros-tuh-toh-MEG-uh-lee','sign','easy'),
 ('prostatorrhea','prostat|o|rrhea','discharge from the prostate','pros-tuh-toh-REE-uh','sign','easy'),
 ('prostatovesiculectomy','prostat|o|vesicul|ectomy','surgical removal of the prostate and seminal vesicles','pros-tuh-toh-veh-sik-yoo-LEK-tuh-mee','procedure','hard'),
 ('prostatovesiculitis','prostat|o|vesicul|itis','inflammation of the prostate and seminal vesicles','pros-tuh-toh-veh-sik-yoo-LY-tis','condition','hard'),
 ('pyelitis','pyel|itis','inflammation of the renal pelvis','py-eh-LY-tis','condition','easy'),
 ('pyelocystitis','pyel|o|cyst|itis','inflammation of the renal pelvis and urinary bladder','py-eh-loh-sis-TY-tis','condition','hard'),
 ('pyelocystostomosis','pyel|o|cyst|o|stomosis','surgically connecting the renal pelvis to the urinary bladder','py-eh-loh-sis-toh-stuh-MOH-sis','procedure','hard'),
 ('pyelogram','pyel|o|gram','an x-ray picture of the renal pelvis and ureter','PY-eh-loh-gram','test','easy'),
 ('pyelolithotomy','pyel|o|lith|otomy','an incision into the renal pelvis to remove a stone','py-eh-loh-lih-THOT-uh-mee','procedure','hard'),
 ('pyelopathy','pyel|o|pathy','any disease of the renal pelvis','py-eh-LOP-uh-thee','condition','easy'),
 ('pyeloplasty','pyel|o|plasty','surgical repair of the renal pelvis','PY-eh-loh-plas-tee','procedure','easy'),
 ('pyelostomy','pyel|ostomy','a new opening into the renal pelvis for drainage','py-eh-LOS-tuh-mee','procedure','easy'),
 ('pyelotomy','pyel|otomy','an incision into the renal pelvis','py-eh-LOT-uh-mee','procedure','easy'),
 ('pyeloureterectasia','pyel|o|ureter|ectasia','widening (dilation) of the renal pelvis and ureter','py-eh-loh-yoo-ree-ter-ek-TAY-zhuh','condition','hard'),
 ('pyonephritis','py|o|nephr|itis','inflammation of a kidney with pus','py-oh-neh-FRY-tis','condition','hard'),
 ('pyonephrolithiasis','py|o|nephr|o|lith|iasis','kidney stones with pus in the kidney','py-oh-nef-roh-lih-THY-uh-sis','condition','hard'),
 ('pyopyeloectasis','py|o|pyel|o|ectasis','a widened renal pelvis filled with pus','py-oh-py-eh-loh-EK-tuh-sis','condition','hard'),
 ('pyuria','py|uria','pus (white blood cells) in the urine, a sign of infection','py-YOO-ree-uh','sign','easy'),
 ('renal','ren|al','pertaining to the kidney','REE-nul','descriptive word','easy'),
 ('resectoscope','re|sect|o|scope','a scope passed through the urethra to view and cut away tissue, usually from the prostate','ree-SEK-toh-skohp','instrument','hard'),
 ('seminoma','semin|oma','a cancer of the testis that starts in sperm-forming cells','sem-ih-NOH-muh','condition','medium'),
 ('spermatocele','spermat|o|cele','a fluid-filled cyst near the testis that contains sperm','sper-MAT-oh-seel','condition','medium'),
 ('spermatogenesis','spermat|o|genesis','the production of sperm','sper-mat-oh-JEN-eh-sis','process','medium'),
 ('spermatolysis','spermat|o|lysis','the destruction of sperm','sper-muh-TOL-ih-sis','process','medium'),
 ('spermicide','sperm|i|cide','a substance that kills sperm','SPER-mih-side','medication','medium'),
 ('spermolytic','sperm|o|lytic','destroying sperm','sper-moh-LIT-ik','descriptive word','medium'),
 ('testitis','test|itis','inflammation of a testis (same as orchitis)','tes-TY-tis','condition','easy'),
 ('ultrasonography','ultra|son|o|graphy','imaging with high-frequency sound waves (ultrasound)','ul-truh-soh-NOG-ruh-fee','test','medium'),
 ('uremia','ur|emia','a buildup of waste products in the blood because the kidneys are failing','yoo-REE-mee-uh','condition','easy'),
 ('ureteralgia','ureter|algia','pain in a ureter','yoo-ree-ter-AL-juh','symptom','easy'),
 ('ureteritis','ureter|itis','inflammation of a ureter','yoo-ree-ter-EYE-tis','condition','easy'),
 ('ureterocele','ureter|o|cele','a balloon-like bulge of the end of a ureter into the bladder','yoo-REE-ter-oh-seel','condition','easy'),
 ('ureteroileostomy','ureter|o|ile|ostomy','connecting the ureters to a piece of the ileum to drain urine out of the body','yoo-ree-ter-oh-il-ee-OS-tuh-mee','procedure','hard'),
 ('ureterolithiasis','ureter|o|lith|iasis','a stone in a ureter','yoo-ree-ter-oh-lih-THY-uh-sis','condition','hard'),
 ('ureteronephrectomy','ureter|o|nephr|ectomy','surgical removal of a ureter and its kidney','yoo-ree-ter-oh-neh-FREK-tuh-mee','procedure','hard'),
 ('ureteroplasty','ureter|o|plasty','surgical repair of a ureter','yoo-REE-ter-oh-plas-tee','procedure','easy'),
 ('ureteropyelitis','ureter|o|pyel|itis','inflammation of a ureter and the renal pelvis','yoo-ree-ter-oh-py-eh-LY-tis','condition','hard'),
 ('ureteropyelonephritis','ureter|o|pyel|o|nephr|itis','inflammation of a ureter, the renal pelvis and the kidney','yoo-ree-ter-oh-py-eh-loh-neh-FRY-tis','condition','hard'),
 ('ureterorrhaphy','ureter|o|rrhaphy','suturing of a ureter','yoo-ree-ter-OR-uh-fee','procedure','easy'),
 ('ureteroscopy','ureter|o|scopy','examination inside a ureter with a scope','yoo-ree-ter-OS-kuh-pee','test','easy'),
 ('ureterostenosis','ureter|o|stenosis','narrowing of a ureter','yoo-ree-ter-oh-steh-NOH-sis','condition','easy'),
 ('urethrectomy','urethr|ectomy','surgical removal of the urethra','yoo-reh-THREK-tuh-mee','procedure','easy'),
 ('urethritis','urethr|itis','inflammation of the urethra','yoo-reh-THRY-tis','condition','easy'),
 ('urethrocystitis','urethr|o|cyst|itis','inflammation of the urethra and urinary bladder','yoo-ree-throh-sis-TY-tis','condition','hard'),
 ('urethrodynia','urethr|o|dynia','pain in the urethra','yoo-ree-throh-DIN-ee-uh','symptom','easy'),
 ('urethrogram','urethr|o|gram','an x-ray picture of the urethra','yoo-REE-throh-gram','test','easy'),
 ('urethropexy','urethr|o|pexy','surgically fixing the urethra in place, often to treat leaking urine','yoo-REE-throh-pek-see','procedure','easy'),
 ('urethroplasty','urethr|o|plasty','surgical repair of the urethra','yoo-REE-throh-plas-tee','procedure','easy'),
 ('urethrorrhea','urethr|o|rrhea','discharge from the urethra','yoo-ree-throh-REE-uh','sign','easy'),
 ('urethroscope','urethr|o|scope','an instrument for looking inside the urethra','yoo-REE-throh-skohp','instrument','easy'),
 ('urethroscopy','urethr|o|scopy','examination inside the urethra with a scope','yoo-reh-THROS-kuh-pee','test','easy'),
 ('urethrospasm','urethr|o|spasm','a sudden, involuntary tightening of the urethra','yoo-REE-throh-spaz-um','symptom','easy'),
 ('urethrostenosis','urethr|o|stenosis','narrowing of the urethra','yoo-ree-throh-steh-NOH-sis','condition','easy'),
 ('urethrotomy','urethr|otomy','an incision into the urethra, often to open a narrowing','yoo-reh-THROT-uh-mee','procedure','easy'),
 ('urocyanosis','ur|o|cyan|osis','blue coloring of the urine','yoo-roh-sy-uh-NOH-sis','sign','hard'),
 ('urodynia','ur|o|dynia','pain when urinating','yoo-roh-DIN-ee-uh','symptom','easy'),
 ('urologist','ur|o|logist','a doctor who specializes in the urinary tract and male reproductive system','yoo-ROL-uh-jist','specialist','easy'),
 ('uropathy','ur|o|pathy','any disease of the urinary tract','yoo-ROP-uh-thee','condition','easy'),
 ('uropoiesis','ur|o|poiesis','the production of urine by the kidneys','yoo-roh-poy-EE-sis','process','medium'),
 ('urostomy','ur|ostomy','a surgical opening that lets urine leave the body through the abdomen into a pouch','yoo-ROS-tuh-mee','procedure','easy'),
 ('uroxanthin','ur|o|xanth|in','the yellow pigment in urine','yoo-roh-ZAN-thin','substance','hard'),
 ('varicocele','varic|o|cele','enlarged, twisted veins in the scrotum','VAIR-ih-koh-seel','condition','medium'),
 ('vasovasostomy','vas|o|vas|ostomy','reconnecting the cut ends of the vas deferens (reversing a vasectomy)','vay-soh-vuh-SOS-tuh-mee','procedure','hard'),
 ('vesicocele','vesic|o|cele','a hernia of the urinary bladder (same as cystocele)','VES-ih-koh-seel','condition','easy'),
 ('vesicostomy','vesic|ostomy','a new surgical opening into the urinary bladder','ves-ih-KOS-tuh-mee','procedure','easy'),
 ('vesicotomy','vesic|otomy','an incision into the urinary bladder','ves-ih-KOT-uh-mee','procedure','easy'),
 ('vesiculectomy','vesicul|ectomy','surgical removal of a seminal vesicle','veh-sik-yoo-LEK-tuh-mee','procedure','easy'),
]
# Phrases and words that don't split into standard parts. (term, definition, pronunciation or None, Sort category or None)
PHRASES12 = [
 ('antispasmodic','a medicine that relieves muscle spasms','an-tee-spaz-MOD-ik','tx'),
 ('benign prostatic hyperplasia','noncancerous enlargement of the prostate gland (BPH)','bih-NINE pros-TAT-ik hy-per-PLAY-zhuh','dx'),
 ('blood urea nitrogen','BUN: a blood test of urea, a waste product the kidneys remove',None,'test'),
 ('digital rectal exam','DRE: the provider feels the prostate with a gloved finger in the rectum',None,'test'),
 ('ejaculation','release of semen from the penis','ih-jak-yoo-LAY-shun',None),
 ('epididymo-orchitis','inflammation of the epididymis and testis','ep-ih-did-ih-moh-or-KY-tis','dx'),
 ('extracorporeal shock wave lithotripsy','ESWL: breaking up kidney stones with shock waves aimed from outside the body','eks-truh-kor-POR-ee-ul','tx'),
 ('fulguration','destroying tissue with a high-frequency electric current','ful-gyuh-RAY-shun','tx'),
 ('gonads','the sex glands: testes in males, ovaries in females','GOH-nadz','body'),
 ('hypospadias','a birth defect in which the urethral opening is on the underside of the penis','hy-poh-SPAY-dee-us','dx'),
 ('incontinence','not being able to control urination (or bowel movements)','in-KON-tih-nens','sx'),
 ('intracorporeal lithotripsy','breaking up stones with a device passed inside the body','in-truh-kor-POR-ee-ul','tx'),
 ('kidney dialysis','filtering wastes from the blood with a machine when the kidneys fail',None,'tx'),
 ('meatal stenosis','narrowing of the urinary opening (meatus)','mee-AY-tul steh-NOH-sis','dx'),
 ('nocturnal enuresis','bedwetting during sleep','nok-TUR-nul en-yoo-REE-sis','sx'),
 ('phimosis','foreskin too tight to pull back over the tip of the penis','fy-MOH-sis','dx'),
 ('polycystic kidney disease','an inherited disease in which many fluid-filled cysts grow in the kidneys',None,'dx'),
 ('priapism','a prolonged, painful erection not caused by arousal; a medical emergency','PRY-uh-piz-um','sx'),
 ('renal angiogram','an x-ray picture of the kidney\'s blood vessels',None,'test'),
 ('renal angiography','the process of taking x-ray pictures of the kidney\'s blood vessels',None,'test'),
 ('renal angioplasty','opening a narrowed kidney artery with a small balloon',None,'tx'),
 ('renal arteriogram','an x-ray picture of the kidney\'s arteries',None,'test'),
 ('renal cell carcinoma','the most common type of kidney cancer',None,'dx'),
 ('renal failure','the kidneys can no longer filter wastes from the blood well enough',None,'dx'),
 ('renal ischemia','too little blood flow to a kidney',None,'dx'),
 ('retrograde pyelogram','an x-ray of the ureter and kidney taken after dye is passed up from the bladder',None,'test'),
 ('stress urinary incontinence','SUI: leaking urine when coughing, sneezing, laughing or lifting',None,'sx'),
 ('testicular carcinoma','cancer of the testis',None,'dx'),
 ('transrectal ultrasonography','an ultrasound of the prostate using a probe placed in the rectum',None,'test'),
 ('transurethral resection of the prostate','TURP: removing part of the prostate with a scope passed through the urethra',None,'tx'),
 ('urinalysis','a lab test of a urine specimen','yoo-rih-NAL-ih-sis','test'),
 ('urinary catheterization','placing a tube into the bladder to drain urine',None,'tx'),
 ('urinary tract infection','UTI: an infection anywhere in the urinary tract, most often the bladder',None,'dx'),
 ('vas deferens','the duct that carries sperm from the epididymis toward the urethra','vas DEF-er-enz','body'),
 ('vesicoureteral reflux','urine flowing backward from the bladder up into the ureters','ves-ih-koh-yoo-REE-ter-ul','dx'),
 ('voiding','urinating',None,None),
]
