# MedDecode master list (draft for instructor review).
# PARTS: id -> (form, type, meaning, pronunciation, body system, used as a Tiles pair?, conflict key)
# The conflict key keeps look-alike meanings ("below", "within", "disease") off the same Tiles board.
PARTS = {
 # prefixes
 'a':      ('a-, an-','prefix','without, absence of','ay, an','General',True,None),
 'brady':  ('brady-','prefix','slow','BRAD-ee','General',True,None),
 'tachy':  ('tachy-','prefix','fast, rapid','TAK-ee','General',True,None),
 'dys':    ('dys-','prefix','difficult, painful, abnormal','dis','General',True,None),
 'hyper':  ('hyper-','prefix','above normal, excessive','HY-per','General',True,'above'),
 'hypo':   ('hypo-','prefix','below normal, deficient','HY-poh','General',True,'below'),
 'peri':   ('peri-','prefix','around','PAIR-ee','General',True,None),
 'endo':   ('endo-','prefix','within, inner','EN-doh','General',True,'within'),
 'sub':    ('sub-','prefix','below, under','sub','General',True,'below'),
 'poly':   ('poly-','prefix','many, much','POL-ee','General',True,None),
 'hemi':   ('hemi-','prefix','half','HEM-ee','General',True,None),
 'dia':    ('dia-','prefix','through, complete','DY-uh','General',True,None),
 # roots shown as pictures in Tiles
 'cardi':  ('cardi/o','root','heart','KAR-dee-oh','Cardiovascular',True,'heart'),
 'hepat':  ('hepat/o','root','liver','HEP-uh-toh','Digestive',True,None),
 'nephr':  ('nephr/o','root','kidney','NEF-roh','Urinary',True,None),
 'oste':   ('oste/o','root','bone','OS-tee-oh','Skeletal',True,None),
 # roots as text
 'gastr':  ('gastr/o','root','stomach','GAS-troh','Digestive',True,None),
 'enter':  ('enter/o','root','small intestine','EN-ter-oh','Digestive',True,None),
 'col':    ('col/o','root','colon (large intestine)','KOH-loh','Digestive',True,None),
 'append': ('append/o','root','appendix','uh-PEN-doh','Digestive',True,None),
 'cholecyst':('cholecyst/o','root','gallbladder','koh-lee-SIS-toh','Digestive',True,None),
 'phag':   ('phag/o','root','eat, swallow','FAY-goh','Digestive',True,None),
 'neur':   ('neur/o','root','nerve','NOO-roh','Nervous',True,None),
 'encephal':('encephal/o','root','brain','en-SEF-uh-loh','Nervous',True,None),
 'cephal': ('cephal/o','root','head','SEF-uh-loh','Nervous',True,None),
 'crani':  ('crani/o','root','skull','KRAY-nee-oh','Skeletal',True,None),
 'my':     ('my/o','root','muscle','MY-oh','Muscular',True,None),
 'arthr':  ('arthr/o','root','joint','AR-throh','Skeletal',True,None),
 'chondr': ('chondr/o','root','cartilage','KON-droh','Skeletal',True,None),
 'dermat': ('dermat/o','root','skin','DER-muh-toh','Integumentary',True,'skin'),
 'lip':    ('lip/o','root','fat','LIP-oh','Integumentary',True,None),
 'rhin':   ('rhin/o','root','nose','RY-noh','Respiratory',True,None),
 'laryng': ('laryng/o','root','larynx (voice box)','luh-RING-goh','Respiratory',True,None),
 'trache': ('trache/o','root','trachea (windpipe)','TRAY-kee-oh','Respiratory',True,None),
 'bronch': ('bronch/o','root','bronchus (airway)','BRONG-koh','Respiratory',True,None),
 'pulmon': ('pulmon/o','root','lung','PUL-muh-noh','Respiratory',True,None),
 'cyst':   ('cyst/o','root','urinary bladder','SIS-toh','Urinary',True,None),
 'hemat':  ('hemat/o','root','blood','HEE-muh-toh','Blood',True,None),
 'angi':   ('angi/o','root','blood vessel','AN-jee-oh','Cardiovascular',True,None),
 'phleb':  ('phleb/o','root','vein','FLEB-oh','Cardiovascular',True,None),
 'thromb': ('thromb/o','root','clot','THROM-boh','Blood',True,None),
 'glyc':   ('glyc/o','root','sugar, glucose','GLY-koh','Endocrine',True,None),
 'cyan':   ('cyan/o','root','blue','SY-uh-noh','General',True,None),
 'erythr': ('erythr/o','root','red','eh-RITH-roh','General',True,None),
 'leuk':   ('leuk/o','root','white','LOO-koh','General',True,None),
 'path':   ('path/o','root','disease','PATH-oh','General',True,'disease'),
 'ot':     ('ot/o','root','ear','OH-toh','Sensory',True,None),
 'ophthalm':('ophthalm/o','root','eye','off-THAL-moh','Sensory',True,None),
 'gloss':  ('gloss/o','root','tongue','GLOS-oh','Oral',True,None),
 'odont':  ('odont/o','root','tooth','oh-DON-toh','Oral',True,'tooth'),
 'gingiv': ('gingiv/o','root','gums','JIN-jih-voh','Oral',True,None),
 # roots used in terms but not as Tiles pairs
 'tension':('tension','root','pressure','TEN-shun','General',False,None),
 'tonsill':('tonsill/o','root','tonsils','TON-sih-loh','Lymphatic',False,None),
 'cutane': ('cutane/o','root','skin','kyoo-TAY-nee-oh','Integumentary',False,'skin'),
 'por':    ('por/o','root','pore, small opening','POR-oh','General',False,None),
 'electr': ('electr/o','root','electricity','ee-LEK-troh','General',False,None),
 'colon':  ('colon/o','root','colon','koh-LON-oh','Digestive',False,None),
 # suffixes
 'itis':   ('-itis','suffix','inflammation','EYE-tis','General',True,None),
 'ectomy': ('-ectomy','suffix','surgical removal','EK-tuh-mee','General',True,None),
 'otomy':  ('-otomy','suffix','incision, cutting into','OT-uh-mee','General',True,None),
 'ostomy': ('-ostomy','suffix','new surgical opening','OS-tuh-mee','General',True,None),
 'algia':  ('-algia','suffix','pain','AL-jee-uh','General',True,None),
 'megaly': ('-megaly','suffix','enlargement','MEG-uh-lee','General',True,None),
 'logy':   ('-logy','suffix','study of','LOH-jee','General',True,None),
 'scopy':  ('-scopy','suffix','visual examination','SKOH-pee','General',True,None),
 'plasty': ('-plasty','suffix','surgical repair','PLAS-tee','General',True,None),
 'gram':   ('-gram','suffix','record, picture','gram','General',True,None),
 'emia':   ('-emia','suffix','blood condition','EE-mee-uh','General',True,None),
 'osis':   ('-osis','suffix','abnormal condition','OH-sis','General',True,None),
 'oma':    ('-oma','suffix','tumor, mass','OH-muh','General',True,None),
 'pathy':  ('-pathy','suffix','disease','PATH-ee','General',True,'disease'),
 'cyte':   ('-cyte','suffix','cell','site','General',True,None),
 'pnea':   ('-pnea','suffix','breathing','NEE-uh','General',True,None),
 'uria':   ('-uria','suffix','urine condition','YOO-ree-uh','General',True,None),
 'rrhea':  ('-rrhea','suffix','flow, discharge','REE-uh','General',True,None),
 'plegia': ('-plegia','suffix','paralysis','PLEE-juh','General',True,None),
 'penia':  ('-penia','suffix','deficiency, too few','PEE-nee-uh','General',True,None),
 # suffixes used in terms but not as Tiles pairs
 'ia':     ('-ia','suffix','condition','EE-uh','General',False,None),
 'ous':    ('-ous','suffix','pertaining to','us','General',False,None),
}

# TERMS: (word, parts, definition, pronunciation, what it names, body system, level)
# parts: list of (letters, part id); a combining vowel is ('o','cv').
T = lambda *a: a
TERMS = [
 T('gastritis',[('gastr','gastr'),('itis','itis')],'inflammation of the stomach','gas-TRY-tis','condition','Digestive','easy'),
 T('hepatitis',[('hepat','hepat'),('itis','itis')],'inflammation of the liver','hep-uh-TY-tis','condition','Digestive','easy'),
 T('nephritis',[('nephr','nephr'),('itis','itis')],'inflammation of the kidney','neh-FRY-tis','condition','Urinary','easy'),
 T('dermatitis',[('dermat','dermat'),('itis','itis')],'inflammation of the skin','der-muh-TY-tis','condition','Integumentary','easy'),
 T('cystitis',[('cyst','cyst'),('itis','itis')],'inflammation of the urinary bladder','sis-TY-tis','condition','Urinary','easy'),
 T('laryngitis',[('laryng','laryng'),('itis','itis')],'inflammation of the larynx (voice box)','lair-in-JY-tis','condition','Respiratory','easy'),
 T('phlebitis',[('phleb','phleb'),('itis','itis')],'inflammation of a vein','fleh-BY-tis','condition','Cardiovascular','easy'),
 T('encephalitis',[('encephal','encephal'),('itis','itis')],'inflammation of the brain','en-sef-uh-LY-tis','condition','Nervous','easy'),
 T('glossitis',[('gloss','gloss'),('itis','itis')],'inflammation of the tongue','glos-SY-tis','condition','Oral','easy'),
 T('gingivitis',[('gingiv','gingiv'),('itis','itis')],'inflammation of the gums','jin-jih-VY-tis','condition','Oral','easy'),
 T('colitis',[('col','col'),('itis','itis')],'inflammation of the colon','koh-LY-tis','condition','Digestive','easy'),
 T('appendectomy',[('append','append'),('ectomy','ectomy')],'surgical removal of the appendix','ap-en-DEK-tuh-mee','procedure','Digestive','easy'),
 T('tonsillectomy',[('tonsill','tonsill'),('ectomy','ectomy')],'surgical removal of the tonsils','ton-sih-LEK-tuh-mee','procedure','Lymphatic','easy'),
 T('cholecystectomy',[('cholecyst','cholecyst'),('ectomy','ectomy')],'surgical removal of the gallbladder','koh-lee-sis-TEK-tuh-mee','procedure','Digestive','easy'),
 T('craniotomy',[('crani','crani'),('otomy','otomy')],'an incision into the skull','kray-nee-OT-uh-mee','procedure','Nervous','easy'),
 T('tracheostomy',[('trache','trache'),('ostomy','ostomy')],'a new surgical opening into the trachea (windpipe)','tray-kee-OS-tuh-mee','procedure','Respiratory','easy'),
 T('rhinoplasty',[('rhin','rhin'),('o','cv'),('plasty','plasty')],'surgical repair of the nose','RY-noh-plas-tee','procedure','Respiratory','easy'),
 T('angioplasty',[('angi','angi'),('o','cv'),('plasty','plasty')],'surgical repair of a blood vessel','AN-jee-oh-plas-tee','procedure','Cardiovascular','easy'),
 T('cardiomegaly',[('cardi','cardi'),('o','cv'),('megaly','megaly')],'enlargement of the heart','kar-dee-oh-MEG-uh-lee','sign','Cardiovascular','easy'),
 T('hepatomegaly',[('hepat','hepat'),('o','cv'),('megaly','megaly')],'enlargement of the liver','hep-uh-toh-MEG-uh-lee','sign','Digestive','easy'),
 T('neuralgia',[('neur','neur'),('algia','algia')],'nerve pain','noo-RAL-juh','symptom','Nervous','easy'),
 T('myalgia',[('my','my'),('algia','algia')],'muscle pain','my-AL-juh','symptom','Muscular','easy'),
 T('cephalalgia',[('cephal','cephal'),('algia','algia')],'headache','sef-uh-LAL-juh','symptom','Nervous','easy'),
 T('otalgia',[('ot','ot'),('algia','algia')],'earache','oh-TAL-juh','symptom','Sensory','easy'),
 T('odontalgia',[('odont','odont'),('algia','algia')],'toothache','oh-don-TAL-jee-uh','symptom','Oral','easy'),
 T('arthralgia',[('arthr','arthr'),('algia','algia')],'joint pain','ar-THRAL-jee-uh','symptom','Skeletal','easy'),
 T('dermatology',[('dermat','dermat'),('o','cv'),('logy','logy')],'the study of the skin','der-muh-TOL-uh-jee','specialty','Integumentary','easy'),
 T('neurology',[('neur','neur'),('o','cv'),('logy','logy')],'the study of the nervous system','noo-ROL-uh-jee','specialty','Nervous','easy'),
 T('pathology',[('path','path'),('o','cv'),('logy','logy')],'the study of disease','puh-THOL-uh-jee','specialty','General','easy'),
 T('ophthalmology',[('ophthalm','ophthalm'),('o','cv'),('logy','logy')],'the study of the eye','off-thal-MOL-uh-jee','specialty','Sensory','easy'),
 T('bronchoscopy',[('bronch','bronch'),('o','cv'),('scopy','scopy')],'visual examination of the airways with a scope','brong-KOS-kuh-pee','test','Respiratory','easy'),
 T('lipoma',[('lip','lip'),('oma','oma')],'a benign (non-cancerous) tumor made of fat','lih-POH-muh','condition','Integumentary','easy'),
 T('thrombosis',[('thromb','thromb'),('osis','osis')],'an abnormal condition of a blood clot forming in a vessel','throm-BOH-sis','condition','Cardiovascular','easy'),
 T('cyanosis',[('cyan','cyan'),('osis','osis')],'bluish discoloration of the skin','sy-uh-NOH-sis','sign','General','easy'),
 T('neuropathy',[('neur','neur'),('o','cv'),('pathy','pathy')],'disease or damage of the nerves','noo-ROP-uh-thee','condition','Nervous','easy'),
 T('leukocyte',[('leuk','leuk'),('o','cv'),('cyte','cyte')],'white blood cell','LOO-koh-site','body part','Blood','easy'),
 T('erythrocyte',[('erythr','erythr'),('o','cv'),('cyte','cyte')],'red blood cell','eh-RITH-roh-site','body part','Blood','easy'),
 T('thrombocyte',[('thromb','thromb'),('o','cv'),('cyte','cyte')],'platelet; a cell that helps blood clot','THROM-boh-site','body part','Blood','easy'),
 T('leukopenia',[('leuk','leuk'),('o','cv'),('penia','penia')],'too few white blood cells','loo-koh-PEE-nee-uh','condition','Blood','easy'),
 T('hematuria',[('hemat','hemat'),('uria','uria')],'blood in the urine','hee-muh-TOO-ree-uh','sign','Urinary','easy'),
 T('rhinorrhea',[('rhin','rhin'),('o','cv'),('rrhea','rrhea')],'runny nose; discharge from the nose','ry-noh-REE-uh','symptom','Respiratory','easy'),
 T('anemia',[('an','a'),('emia','emia')],'a lack of red blood cells or hemoglobin','uh-NEE-mee-uh','condition','Blood','medium'),
 T('polyuria',[('poly','poly'),('uria','uria')],'excessive urination','pol-ee-YOOR-ee-uh','symptom','Urinary','medium'),
 T('apnea',[('a','a'),('pnea','pnea')],'absence of breathing','AP-nee-uh','sign','Respiratory','medium'),
 T('tachypnea',[('tachy','tachy'),('pnea','pnea')],'fast breathing','tak-ip-NEE-uh','sign','Respiratory','medium'),
 T('dyspnea',[('dys','dys'),('pnea','pnea')],'difficulty breathing','DISP-nee-uh','symptom','Respiratory','medium'),
 T('bradycardia',[('brady','brady'),('card','cardi'),('ia','ia')],'slow heart rate','brad-ee-KAR-dee-uh','sign','Cardiovascular','medium'),
 T('tachycardia',[('tachy','tachy'),('card','cardi'),('ia','ia')],'fast heart rate','tak-ih-KAR-dee-uh','sign','Cardiovascular','medium'),
 T('hypoglycemia',[('hypo','hypo'),('glyc','glyc'),('emia','emia')],'below-normal blood sugar','hy-poh-gly-SEE-mee-uh','condition','Endocrine','medium'),
 T('hyperglycemia',[('hyper','hyper'),('glyc','glyc'),('emia','emia')],'above-normal blood sugar','hy-per-gly-SEE-mee-uh','condition','Endocrine','medium'),
 T('hypertension',[('hyper','hyper'),('tension','tension')],'abnormally high blood pressure','hy-per-TEN-shun','condition','Cardiovascular','medium'),
 T('pericarditis',[('peri','peri'),('card','cardi'),('itis','itis')],'inflammation of the sac around the heart','pair-ih-kar-DY-tis','condition','Cardiovascular','medium'),
 T('dysphagia',[('dys','dys'),('phag','phag'),('ia','ia')],'difficulty swallowing','dis-FAY-jee-uh','symptom','Digestive','medium'),
 T('hemiplegia',[('hemi','hemi'),('plegia','plegia')],'paralysis of one side of the body','hem-ee-PLEE-juh','sign','Nervous','medium'),
 T('diarrhea',[('dia','dia'),('rrhea','rrhea')],'frequent, loose, watery stools','dy-uh-REE-uh','symptom','Digestive','medium'),
 T('endoscopy',[('endo','endo'),('scopy','scopy')],'visual examination inside the body with a scope','en-DOS-kuh-pee','test','General','medium'),
 T('subcutaneous',[('sub','sub'),('cutane','cutane'),('ous','ous')],'pertaining to below the skin','sub-kyoo-TAY-nee-us','descriptive word','Integumentary','medium'),
 T('gastroenteritis',[('gastr','gastr'),('o','cv'),('enter','enter'),('itis','itis')],'inflammation of the stomach and small intestine','gas-troh-en-ter-EYE-tis','condition','Digestive','hard'),
 T('osteoarthritis',[('oste','oste'),('o','cv'),('arthr','arthr'),('itis','itis')],'inflammation of bone and joint; degenerative joint disease','os-tee-oh-ar-THRY-tis','condition','Skeletal','hard'),
 T('osteoporosis',[('oste','oste'),('o','cv'),('por','por'),('osis','osis')],'a condition of thin, porous bones that break easily','os-tee-oh-puh-ROH-sis','condition','Skeletal','hard'),
 T('electrocardiogram',[('electr','electr'),('o','cv'),('cardi','cardi'),('o','cv'),('gram','gram')],"a record of the heart's electrical activity (ECG or EKG)",'ee-lek-troh-KAR-dee-oh-gram','test','Cardiovascular','hard'),
]
