# 20 new MedDecode Build cases (drafts for instructor review)
C = lambda **k: k
NEW = [
 # Easy
 C(lvl='easy', prog='CCMA', ans=['ot','algia'], tray=['ot','rhin','laryng','odont','algia','itis','rrhea','scopy','peri','endo','a_s','um'],
   text='A mother brings in her 4-year-old, who keeps tugging at his right ear and crying. She says he has complained of ear pain since last night. There is no drainage.',
   q='What is the medical term for his complaint?', say='oh-TAL-juh', body='Ear · sensory system', kind='Symptom',
   facts='Otalgia names the pain. If the ear is inflamed or infected, the diagnosis would be otitis.'),
 C(lvl='easy', prog='CCMA', ans=['dermat','itis'], tray=['dermat','lip','my','oste','itis','oma','algia','logy','sub','peri','a_s','um'],
   text='A patient switched to a new laundry detergent last week. Now she has a red, itchy, inflamed rash on her arms and neck where her clothes touch her skin.',
   q='What is the diagnosis?', say='der-muh-TY-tis', body='Skin · integumentary system', kind='Condition (diagnosis)',
   facts='This kind of rash from something touching the skin is called contact dermatitis.'),
 C(lvl='easy', prog='CNA / Nursing', ans=['phleb','itis'], tray=['phleb','thromb','cardi','hemat','itis','osis','ectomy','oma','peri','endo','a_s','um'],
   text='A resident\'s forearm is warm, red and tender along a vein where an IV was placed yesterday. An ultrasound found no blood clot.',
   q='What is the condition?', say='fleh-BY-tis', body='Vein · cardiovascular system', kind='Condition',
   facts='Report IV-site redness, warmth or pain to the nurse. With a clot, the term would be thrombophlebitis.'),
 C(lvl='easy', prog='All programs', ans=['tonsill','ectomy'], tray=['tonsill','append','laryng','gloss','ectomy','otomy','itis','ostomy','sub','peri','a_s','um'],
   text='A 7-year-old has had strep throat seven times this year, and his tonsils are badly enlarged. The ear, nose and throat surgeon recommends taking them out.',
   q='What is this surgery called?', say='ton-sih-LEK-tuh-mee', body='Tonsils · lymphatic system', kind='Procedure (surgery)',
   facts='-ectomy removes the part. Inflamed tonsils would be tonsillitis.'),
 # Medium
 C(lvl='medium', prog='EMT', ans=['tachy','pnea'], tray=['tachy','brady','dys','a','cardi','rhin','pulmon','pnea','ia','rrhea','a_s','um'],
   text='An EMT counts the breathing of a feverish 8-year-old at rest: 44 breaths per minute. A normal rate for her age is about 18 to 30.',
   q='What term describes this breathing rate?', say='tak-ip-NEE-uh', body='Lungs · respiratory system', kind='Sign (vital sign)',
   facts='Tachypnea is fast breathing; bradypnea is slow; dyspnea is difficult breathing; apnea is no breathing.'),
 C(lvl='medium', prog='CNA / Nursing', ans=['hemi','plegia'], tray=['hemi','a','dys','poly','my','neur','cephal','plegia','algia','pathy','a_s','um'],
   text='A resident who had a stroke last year cannot move his right arm or his right leg at all. His left side is strong.',
   q='What term describes his condition?', say='hem-ee-PLEE-juh', body='Brain and nerves · nervous system', kind='Sign',
   facts='Hemiplegia is paralysis of one side. Weakness of one side, without full paralysis, is hemiparesis.'),
 C(lvl='medium', prog='CNA / Nursing', ans=['sub','cutane','ous'], tray=['sub','epi','endo','peri','cutane','dermat','my','ous','al','itis','a_s','um'],
   text='The nurse explains that the insulin injection goes into the fatty tissue just under the skin, not into the muscle.',
   q='What word describes this type of injection?', say='sub-kyoo-TAY-nee-us', body='Skin and the fat beneath it', kind='Descriptive word',
   facts='Subcutaneous is often abbreviated SubQ. An injection into a muscle is intramuscular (IM).'),
 C(lvl='medium', prog='CCMA', ans=['dia','rrhea'], tray=['dia','dys','a','poly','gastr','enter','col','rrhea','itis','uria','a_s','um'],
   text='A patient calls the clinic. Since eating at a buffet two days ago, she has had loose, watery stools six times a day.',
   q='What is the medical term for her symptom?', say='dy-uh-REE-uh', body='Intestines · digestive system', kind='Symptom',
   facts='dia- (through) + -rrhea (flow). Watch for dehydration: dry mouth, dizziness, little urine.'),
 C(lvl='medium', prog='CNA / Nursing', ans=['an','emia'], tray=['an','a','hyper','poly','hemat','leuk','glyc','emia','uria','cyte','a_s','is'],
   text='A resident has been very tired and short of breath on the stairs. Her skin looks pale, and her lab results show a low red blood cell count.',
   q='What is the condition?', say='uh-NEE-mee-uh', body='Blood', kind='Condition',
   facts='an- (without) + -emia (blood condition): the blood can\'t carry enough oxygen, which causes tiredness and paleness.'),
 C(lvl='medium', prog='CCMA', ans=['endo','scopy'], tray=['endo','peri','epi','bronch','laryng','cardi','scopy','gram','logy','itis','a_s','um'],
   text='The doctor explains that she will pass a thin, flexible, lighted tube with a camera into the patient\'s body to look inside.',
   q='What is the general term for this kind of examination?', say='en-DOS-kuh-pee', body='Inside the body (depends on where the scope goes)', kind='Test',
   facts='Specific types are named for the body part: bronchoscopy (airways), colonoscopy (colon), laryngoscopy (larynx).'),
 C(lvl='medium', prog='All programs', ans=['poly','uria'], tray=['poly','an','dys','olig','hemat','glyc','nephr','uria','emia','itis','a_s','is'],
   text='A 15-year-old has been unusually thirsty and is urinating large amounts many times a day and night. His blood sugar is high.',
   q='What is the term for the large amount of urine?', say='pol-ee-YOOR-ee-uh', body='Kidneys and bladder · urinary system', kind='Symptom',
   facts='Excessive thirst (polydipsia) and polyuria are classic warning signs of diabetes.'),
 C(lvl='medium', prog='CCMA', ans=['hyper','tension'], tray=['hyper','hypo','brady','tachy','tension','cardi','glyc','ia','emia','megaly','a_s','um'],
   text='A patient\'s blood pressure is 168/102. After five minutes of rest it is rechecked at 166/100.',
   q='What condition do these readings show?', say='hy-per-TEN-shun', body='Heart and blood vessels · cardiovascular system', kind='Condition',
   facts='Record both readings. The opposite, low blood pressure, is hypotension.'),
 C(lvl='medium', prog='All programs', ans=['poly','neur','pathy'], tray=['poly','hemi','a','dys','neur','my','cephal','pathy','algia','plegia','a_s','um'],
   text='A patient with long-term diabetes has numbness, tingling and burning pain in both feet and both hands. Many nerves are damaged.',
   q='What is the term for this condition, which affects many nerves?', say='pol-ee-noo-ROP-uh-thee', body='Nerves · nervous system', kind='Condition',
   facts='Check the feet of patients with diabetic neuropathy every day; they may not feel injuries.'),
 # Hard
 C(lvl='hard', prog='All programs', ans=['oste','por','osis'], tray=['oste','por','arthr','chondr','osis','itis','oma','algia','peri','poly','a_s','um'],
   text='An 80-year-old woman broke her wrist in a minor fall. A bone density scan shows her bones are thin and full of tiny holes.',
   q='What is the diagnosis?', say='os-tee-oh-puh-ROH-sis', body='Bones · skeletal system', kind='Condition (diagnosis)',
   facts='Fall prevention matters: a minor fall can break a bone weakened by osteoporosis.'),
 C(lvl='hard', prog='All programs', ans=['electr','encephal','gram'], tray=['electr','encephal','cardi','my','gram','graphy','graph','itis','endo','peri','a_s','um'],
   text='A teenager had a seizure at school. The neurologist orders a test that records the brain\'s electrical activity on a printout.',
   q='What is the printed record called?', say='ee-lek-troh-en-SEF-uh-loh-gram', body='Brain · nervous system', kind='Test (the record)',
   facts='Abbreviated EEG. -gram is the record; -graphy is the process; -graph is the machine.'),
 C(lvl='hard', prog='CNA / Nursing', ans=['thromb','phleb','itis'], tray=['thromb','phleb','angi','hemat','itis','osis','oma','plasty','peri','endo','a_s','um'],
   text='A patient has a painful, red, swollen vein in her calf. An ultrasound shows a blood clot inside that inflamed vein.',
   q='What is the diagnosis?', say='throm-boh-fleh-BY-tis', body='Vein · cardiovascular system', kind='Condition (diagnosis)',
   facts='Never massage a leg with a suspected clot; report it to the nurse right away.'),
 C(lvl='hard', prog='EMT', ans=['laryng','trache','bronch','itis'], tray=['laryng','trache','bronch','pneumon','itis','scopy','ostomy','endo','peri','us','i','a_s'],
   text='A 2-year-old has a barking, seal-like cough and noisy breathing at night. Her larynx, trachea and bronchi are all inflamed. This illness is commonly called croup.',
   q='What is the medical name for croup?', say='luh-ring-goh-tray-kee-oh-brong-KY-tis', body='Upper and lower airway · respiratory system', kind='Condition (diagnosis)',
   facts='Three roots, joined in order from the top of the airway down, each keeping its o.'),
 C(lvl='hard', prog='All programs', ans=['my','cardi','itis'], tray=['my','cardi','arthr','itis','algia','ia','megaly','peri','endo','tachy','um','a_s'],
   text='After a viral illness, a 19-year-old athlete has chest pain and a fast heart rate. Tests show inflammation of the heart muscle itself.',
   q='What is the diagnosis?', say='my-oh-kar-DY-tis', body='Heart muscle · cardiovascular system', kind='Condition (diagnosis)',
   facts='Compare: pericarditis (sac around the heart), endocarditis (inner lining), myocarditis (the muscle).'),
 C(lvl='hard', prog='All programs', ans=['gastr','enter','logy'], tray=['gastr','enter','col','hepat','logy','itis','scopy','ostomy','endo','epi','a_s','um'],
   text='A patient with long-lasting stomach and bowel problems is referred to a specialist in diseases of the stomach and intestines.',
   q='What is the name of this medical specialty?', say='gas-troh-en-ter-OL-uh-jee', body='Stomach and intestines · digestive system', kind='Specialty',
   facts='A doctor in this specialty is a gastroenterologist.'),
 C(lvl='hard', prog='All programs', ans=['ot','rhin','laryng','logy'], tray=['ot','rhin','laryng','odont','logy','itis','algia','rrhea','peri','endo','a_s','um'],
   text='A child with repeated ear infections, a stuffy nose and a hoarse voice is referred to an ear, nose and throat (ENT) specialist.',
   q='What is the full name of this specialty?', say='oh-toh-ry-noh-lair-in-GOL-uh-jee', body='Ear, nose and throat', kind='Specialty',
   facts='The roots go in the same order as "ear, nose and throat." Most people just say ENT.'),
]
