# 31 new MedDecode Build cases (Oct 2026) so every Acquiring Medical Language chapter has cases. Drafts for instructor review.
C = lambda **k: k
NEW2 = [
 # Ch 2 Health records
 C(lvl='medium', prog='CCMA', ans=['eti','logy'], tray=['eti','path','neur','gnos','logy','is','pathy','dia','pro','itis','a_s','um'],
   text='A patient asks what caused her rare autoimmune disease. The provider explains that doctors still do not fully know what causes it.',
   q='What is the term for the cause of a disease?', say='ee-tee-OL-uh-jee', body='Health record term', kind='Concept',
   facts='Health records often list a condition\'s etiology as "unknown." Compare diagnosis (what it is) and prognosis (how it will turn out).'),
 # Ch 3 Integumentary
 C(lvl='easy', prog='CCMA', ans=['melan','oma'], tray=['melan','lip','dermat','cyan','oma','osis','itis','logy','sub','peri','ic','a_s'],
   text='A dermatologist removes a dark mole with uneven borders and several colors from a patient\'s back. The lab reports it is a cancer of the skin\'s pigment cells.',
   q='What is the diagnosis?', say='mel-uh-NOH-muh', body='Skin · integumentary system', kind='Condition (diagnosis)',
   facts='Melanoma is the most dangerous skin cancer. Warning signs follow ABCDE: asymmetry, border, color, diameter and evolving (changing).'),
 C(lvl='medium', prog='CNA / Nursing', ans=['intra','derm','al'], tray=['intra','sub','hypo','peri','derm','cutane','my','al','ic','ous','itis','oma'],
   text='The nurse gives a TB skin test. She injects a tiny amount of fluid into the skin itself, not under it, and a small pale bump forms.',
   q='What word describes this kind of injection?', say='in-truh-DER-mul', body='Skin · integumentary system', kind='Descriptive word',
   facts='Intradermal (ID) goes within the skin. Subcutaneous (SubQ) goes under the skin, into the fat. Intramuscular (IM) goes into a muscle.'),
 C(lvl='hard', prog='CCMA', ans=['onych','myc','osis'], tray=['onych','myc','dermat','oste','osis','itis','oma','ectomy','sub','peri','a_s','um'],
   text='A patient\'s big toenail has become thick, yellow and crumbly. A lab test of a nail clipping finds a fungus.',
   q='What is the diagnosis?', say='on-ih-koh-my-KOH-sis', body='Nail · integumentary system', kind='Condition (diagnosis)',
   facts='onych/o (nail) + myc/o (fungus) + -osis (abnormal condition). Fungal infection of the skin would be dermatomycosis.'),
 C(lvl='easy', prog='All programs', ans=['dermat','plasty'], tray=['dermat','rhin','angi','lip','plasty','ectomy','itis','logy','oma','sub','a_s','um'],
   text='Weeks after a severe burn, a surgeon repairs the damaged skin on a patient\'s arm with a graft taken from his thigh.',
   q='What is the general term for this surgical repair of the skin?', say='DER-muh-toh-plas-tee', body='Skin · integumentary system', kind='Procedure (surgery)',
   facts='-plasty means surgical repair. A skin graft is one kind of dermatoplasty.'),
 # Ch 4 Musculoskeletal
 C(lvl='easy', prog='EMT', ans=['femor','al'], tray=['femor','brachi','carp','cardi','al','ic','itis','algia','ectomy','sub','um','a_s'],
   text='An EMT cannot feel a pulse at an unresponsive patient\'s wrist, so she checks for a pulse in the groin, where a large artery runs beside the thigh bone.',
   q='Which pulse is she checking? (the ___ pulse)', say='FEM-or-ul', body='Thigh and groin · musculoskeletal system', kind='Descriptive word',
   facts='Common pulse sites: radial (wrist), brachial (inner upper arm, used for infants), carotid (neck) and femoral (groin).'),
 C(lvl='medium', prog='EMT', ans=['cervic','al'], tray=['cervic','sacr','vertebr','crani','thorac','al','ic','itis','otomy','ectomy','um','a_s'],
   text='After a diving accident in shallow water, an EMT holds the patient\'s head still and applies a collar to protect the spine in the neck.',
   q='Which part of the spine is being protected? (the ___ spine)', say='SER-vih-kul', body='Neck · spine', kind='Descriptive word',
   facts='The spine from top to bottom: cervical (neck), thoracic (chest), lumbar (lower back), sacral and coccygeal.'),
 C(lvl='easy', prog='CNA / Nursing', ans=['arthr','plasty'], tray=['arthr','oste','chondr','rhin','plasty','scopy','itis','ectomy','algia','centesis','um','a_s'],
   text='A 74-year-old resident returns from the hospital after her worn-out hip joint was replaced with an artificial one.',
   q='What is this surgery called?', say='AR-throh-plas-tee', body='Hip joint · musculoskeletal system', kind='Procedure (surgery)',
   facts='A total hip or knee replacement is an arthroplasty. Follow the hip precautions in her care plan when helping her move.'),
 C(lvl='hard', prog='EMT', ans=['cost','chondr','itis'], tray=['cost','chondr','cardi','oste','peri','inter','itis','al','algia','oma','a_s','um'],
   text='A 19-year-old has sharp chest pain that gets worse when the EMT presses where his ribs meet the breastbone. In the emergency room, heart problems are ruled out.',
   q='What is the doctor\'s diagnosis?', say='kos-toh-kon-DRY-tis', body='Ribs and cartilage · chest', kind='Condition (diagnosis)',
   facts='Chest pain is always treated as possibly cardiac in the field. Costochondritis is diagnosed only after the heart is ruled out.'),
 # Ch 5 Nervous system
 C(lvl='medium', prog='EMT', ans=['para','plegia'], tray=['para','quadri','hemi','dys','plegia','paresis','algia','pathy','neur','my','a_s','um'],
   text='A 22-year-old fell from a roof and landed on his back. He cannot move or feel either leg, but his arms and hands work normally.',
   q='What term describes his loss of movement?', say='pair-uh-PLEE-juh', body='Spinal cord · nervous system', kind='Sign',
   facts='Paraplegia affects both legs (a lower spinal cord injury). Quadriplegia affects all four limbs (a neck injury). Hemiplegia affects one side.'),
 C(lvl='medium', prog='EMT', ans=['a','phas','ia'], tray=['a','dys','hemi','phas','phag','plegia','ia','algia','itis','pnea','um','is'],
   text='A stroke patient clearly hears and understands the EMT and tries to answer, but she cannot get any words out at all.',
   q='What term describes her loss of speech?', say='uh-FAY-zhuh', body='Brain · nervous system', kind='Sign',
   facts='Aphasia is loss of language; dysphasia is difficulty with it. Don\'t confuse them with dysphagia, difficulty swallowing.'),
 C(lvl='easy', prog='CCMA', ans=['mening','itis'], tray=['mening','encephal','cephal','neur','itis','algia','oma','pathy','logy','peri','a_s','um'],
   text='A college student has a high fever, a severe headache and a stiff neck. Tests show the membranes around his brain and spinal cord are inflamed.',
   q='What is the diagnosis?', say='men-in-JY-tis', body='Meninges · nervous system', kind='Condition (diagnosis)',
   facts='Inflammation of the brain itself is encephalitis. Bacterial meningitis is an emergency, and close contacts may need preventive antibiotics.'),
 # Ch 6 Eye and ear
 C(lvl='easy', prog='CCMA', ans=['ot','itis'], tray=['ot','rhin','laryng','ophthalm','itis','algia','rrhea','scope','logy','a_s','um','is'],
   text='A 3-year-old has a fever and keeps pulling at his ear. The provider looks in with a lighted instrument and sees a red, bulging eardrum.',
   q='What is the diagnosis?', say='oh-TY-tis', body='Ear · sensory system', kind='Condition (diagnosis)',
   facts='Ear pain is otalgia; discharge from the ear is otorrhea. A middle ear infection is called otitis media.'),
 C(lvl='medium', prog='CCMA', ans=['ot','scope'], tray=['ot','ophthalm','laryng','endo','scope','scopy','gram','logy','itis','algia','um','a_s'],
   text='Before the provider comes in, the medical assistant sets out the lighted instrument used to look into a patient\'s ear canal.',
   q='What is the instrument called?', say='OH-toh-skohp', body='Ear · sensory system', kind='Instrument',
   facts='-scope names the instrument; -scopy names the exam done with it. The provider uses an otoscope to do an otoscopy.'),
 C(lvl='easy', prog='All programs', ans=['conjunctiv','itis'], tray=['conjunctiv','blephar','ophthalm','retin','itis','pathy','logy','plasty','algia','um','a_s','is'],
   text='Several children at a daycare have red, itchy eyes with a sticky yellow discharge. The doctor calls it pinkeye.',
   q='What is the medical term for pinkeye?', say='kun-junk-tih-VY-tis', body='Eye · sensory system', kind='Condition (diagnosis)',
   facts='Pinkeye spreads easily. Wash hands often and don\'t share towels. Inflammation of the eyelid is blepharitis.'),
 C(lvl='medium', prog='CNA / Nursing', ans=['retin','pathy'], tray=['retin','neur','ophthalm','blephar','pathy','itis','logy','scope','plasty','dys','a_s','um'],
   text='A resident who has had diabetes for 30 years is losing her vision. The eye doctor says the tiny blood vessels at the back of her eye are damaged.',
   q='What is the diagnosis?', say='ret-ih-NOP-uh-thee', body='Retina · eye', kind='Condition (diagnosis)',
   facts='Diabetic retinopathy is a leading cause of blindness. Keep her room uncluttered and tell her where things are.'),
 # Ch 7 Endocrine
 C(lvl='medium', prog='EMT', ans=['hyper','glyc','emia'], tray=['hyper','hypo','poly','glyc','calc','emia','uria','dipsia','leuk','cyte','a_s','um'],
   text='A patient with diabetes is confused and very thirsty, and his breath smells fruity. The glucometer reads 520 mg/dL.',
   q='What condition does the reading show?', say='hy-per-gly-SEE-mee-uh', body='Blood sugar · endocrine system', kind='Condition',
   facts='Normal fasting blood sugar is about 70 to 100 mg/dL. Low blood sugar (hypoglycemia) is under 70 and can look similar, so always check.'),
 C(lvl='medium', prog='CCMA', ans=['poly','dipsia'], tray=['poly','dys','olig','a','dipsia','uria','phag','ia','pnea','emia','glyc','um'],
   text='A 12-year-old\'s mother says he drinks glass after glass of water all day and still says he is thirsty.',
   q='What is the term for his excessive thirst?', say='pol-ee-DIP-see-uh', body='Endocrine system', kind='Symptom',
   facts='Polydipsia (thirst) and polyuria (a lot of urine) together are warning signs of diabetes.'),
 C(lvl='easy', prog='All programs', ans=['thyroid','ectomy'], tray=['thyroid','tonsill','laryng','trache','ectomy','otomy','itis','ism','ostomy','hyper','a_s','um'],
   text='A patient has a large growth on her thyroid gland. The surgeon removes the whole gland.',
   q='What is this surgery called?', say='thy-roy-DEK-tuh-mee', body='Thyroid gland · endocrine system', kind='Procedure (surgery)',
   facts='After a thyroidectomy, the patient takes thyroid hormone pills for life.'),
 C(lvl='hard', prog='CCMA', ans=['hypo','thyroid','ism'], tray=['hypo','hyper','thyroid','crin','glyc','ism','itis','ectomy','emia','logy','a_s','um'],
   text='A patient says she is tired and cold all the time and has gained weight. Blood tests show her thyroid gland is making too little hormone.',
   q='What is the diagnosis?', say='hy-poh-THY-roy-diz-um', body='Thyroid gland · endocrine system', kind='Condition (diagnosis)',
   facts='An underactive thyroid slows the body down. An overactive one (hyperthyroidism) speeds it up: weight loss, feeling hot, fast heart rate.'),
 C(lvl='hard', prog='CCMA', ans=['endo','crin','logy'], tray=['endo','peri','crin','cardi','neur','gastr','logy','scopy','itis','gram','a_s','um'],
   text='The provider refers a patient with a thyroid problem and hard-to-control diabetes to a specialist in glands and hormones.',
   q='What is the name of this medical specialty?', say='en-doh-krih-NOL-uh-jee', body='Glands and hormones · endocrine system', kind='Specialty',
   facts='endo- (within) + crin/o (to secrete) + -logy (study of). The glands secrete hormones into the blood.'),
 # Ch 8 Blood and lymphatic
 C(lvl='easy', prog='EMT', ans=['hemat','oma'], tray=['hemat','lip','my','oste','oma','uria','logy','algia','itis','sub','a_s','um'],
   text='A soccer player was kicked hard in the thigh. There is a firm, swollen, purple lump where blood has collected under the skin.',
   q='What is this collection of blood called?', say='hee-muh-TOH-muh', body='Blood · thigh', kind='Condition',
   facts='-oma usually means tumor, but a hematoma is a mass of blood, not cancer. Ice and elevation help limit swelling.'),
 C(lvl='hard', prog='CCMA', alt=[['thromb','penia']], ans=['thromb','cyt','penia'], tray=['thromb','leuk','erythr','cyt','penia','osis','emia','cyte','an','hemat','a_s','um'],
   text='A patient bruises easily, and her gums bleed when she brushes. Her complete blood count shows very few platelets.',
   q='What is the condition?', say='throm-boh-sy-toh-PEE-nee-uh', body='Platelets · blood', kind='Condition',
   facts='Platelets (thrombocytes) help blood clot. Thrombopenia is a shorter name for the same condition.'),
 C(lvl='easy', prog='All programs', ans=['splen','megaly'], tray=['splen','hepat','cardi','gastr','megaly','ectomy','itis','algia','logy','hyper','a_s','um'],
   text='A teen with mononucleosis has an enlarged, swollen spleen. He is told not to play contact sports for at least a month.',
   q='What is the term for his enlarged spleen?', say='splee-noh-MEG-uh-lee', body='Spleen · lymphatic system', kind='Sign',
   facts='An enlarged spleen can rupture with a hit to the abdomen. That is why contact sports are off-limits.'),
 # Ch 9 Cardiovascular
 C(lvl='medium', prog='EMT', ans=['hypo','tension'], tray=['hypo','hyper','tachy','brady','tension','cardi','ox','ia','emia','glyc','a_s','um'],
   text='After a car crash, a patient is pale, cool and sweaty. His blood pressure is 78/40 and his pulse is weak and fast.',
   q='What term describes his blood pressure?', say='hy-poh-TEN-shun', body='Heart and blood vessels · cardiovascular system', kind='Condition',
   facts='Low blood pressure with a fast, weak pulse after trauma is a sign of shock. Transport rapidly.'),
 # Ch 10 Respiratory
 C(lvl='medium', prog='EMT', ans=['orth','pnea'], tray=['orth','tachy','brady','dys','a','pnea','ia','cardi','pulmon','odont','logy','um'],
   text='An older man with heart failure called 911 at night. He says he cannot breathe when he lies flat, so he has been sleeping sitting up in his recliner.',
   q='What term describes his breathing problem?', say='or-THOP-nee-uh', body='Lungs · respiratory system', kind='Symptom',
   facts='orth/o (straight, upright) + -pnea (breathing): he can breathe only upright. Let him sit up during care and transport.'),
 # Ch 12 Urinary and male reproductive
 C(lvl='medium', prog='CNA / Nursing', ans=['olig','uria'], tray=['olig','poly','an','dys','uria','emia','rrhea','hemat','glyc','pnea','a_s','um'],
   text='A CNA measures a resident\'s urine output: only 200 mL in the last 24 hours, much less than her usual amount.',
   q='What term describes her urine output?', say='ol-ih-GYOO-ree-uh', body='Kidneys · urinary system', kind='Sign',
   facts='Report a drop in urine output to the nurse right away. No urine at all is anuria; painful urination is dysuria.'),
 C(lvl='hard', prog='CCMA', ans=['pyel','nephr','itis'], tray=['pyel','nephr','cyst','ur','itis','logy','ectomy','scopy','lith','iasis','a_s','um'],
   text='A patient has a high fever, chills, pain on one side of her back and burning urination. The provider suspects a bladder infection has spread up into the renal pelvis and kidney.',
   q='What is the diagnosis?', say='py-eh-loh-neh-FRY-tis', body='Kidney and renal pelvis · urinary system', kind='Condition (diagnosis)',
   facts='A bladder infection is cystitis. When it climbs to the kidney and renal pelvis, it becomes pyelonephritis, which is more serious.'),
 C(lvl='hard', prog='All programs', ans=['nephr','lith','iasis'], tray=['nephr','cyst','lith','ur','iasis','itis','ectomy','logy','osis','algia','a_s','um'],
   text='A man has sudden, severe pain in his side that comes in waves. A CT scan shows stones in his kidney.',
   q='What is the diagnosis?', say='nef-roh-lih-THY-uh-sis', body='Kidney · urinary system', kind='Condition (diagnosis)',
   facts='nephr/o (kidney) + lith/o (stone) + -iasis (abnormal condition). Most small stones pass on their own with fluids and pain control.'),
 C(lvl='easy', prog='CCMA', ans=['vas','ectomy'], tray=['vas','orch','prostat','cyst','ectomy','itis','otomy','ostomy','logy','scopy','a_s','um'],
   text='A 38-year-old father of three schedules a minor surgery so he can no longer father children. Part of each duct that carries sperm is removed.',
   q='What is this surgery called?', say='vuh-SEK-tuh-mee', body='Vas deferens · male reproductive system', kind='Procedure (surgery)',
   facts='vas/o (vessel, duct) + -ectomy (removal). It is done in the office with local anesthetic.'),
 # Ch 13 Female reproductive, obstetrics, newborns
 C(lvl='medium', prog='EMT', ans=['post','part','um'], tray=['post','pre','a','dys','part','men','um','rrhea','ia','al','itis','is'],
   text='EMTs are called to a home where a woman gave birth an hour ago. She is now bleeding heavily.',
   q='What term describes the time after childbirth? (___ hemorrhage)', say='pohst-PAR-tum', body='Uterus · female reproductive system', kind='Descriptive word',
   facts='Postpartum hemorrhage is a leading cause of death after childbirth. Massage the uterus (fundal massage) per protocol, treat for shock and transport.'),
 C(lvl='easy', prog='EMT', ans=['pre','nat','al'], tray=['pre','post','neo','nat','men','al','ic','logy','rrhea','dys','a_s','um'],
   text='A pregnant woman in a minor car crash tells the EMT she has seen her obstetrician for every checkup during this pregnancy.',
   q='What word describes the care a woman gets before her baby is born? (___ care)', say='pree-NAY-tul', body='Pregnancy · obstetrics', kind='Descriptive word',
   facts='pre- (before) + nat/o (birth) + -al (pertaining to). Any pregnant patient in a crash should be evaluated, even with no pain.'),
 C(lvl='medium', prog='EMT', ans=['neo','nat','al'], tray=['neo','pre','post','nat','logy','al','ic','ia','cyan','osis','a_s','um'],
   text='After delivering a baby in the back of the ambulance, the EMT checks the newborn\'s breathing, skin color and heart rate in the first minutes of life.',
   q='What word describes the care of a newborn? (___ care)', say='nee-oh-NAY-tul', body='Newborn · obstetrics', kind='Descriptive word',
   facts='neo- (new) + nat/o (birth) + -al. Keep the newborn warm and dry; a bluish color (cyanosis) of the hands and feet is common at first.'),
 C(lvl='easy', prog='CCMA', ans=['mamm','gram'], tray=['mamm','mast','angi','electr','gram','ectomy','itis','scopy','graphy','logy','a_s','um'],
   text='A 45-year-old patient is due for her yearly breast cancer screening. The provider orders an x-ray of both breasts.',
   q='What is the name of the x-ray image that will be taken?', say='MAM-oh-gram', body='Breast · female reproductive system', kind='Test',
   facts='-gram is the picture; -graphy is the process of taking it. Mammography produces a mammogram.'),
 C(lvl='easy', prog='CNA / Nursing', ans=['hyster','ectomy'], tray=['hyster','oophor','mast','salping','ectomy','itis','otomy','scopy','logy','gram','a_s','um'],
   text='A resident tells you she had her uterus removed many years ago, so she no longer has periods.',
   q='What was this surgery called?', say='his-ter-EK-tuh-mee', body='Uterus · female reproductive system', kind='Procedure (surgery)',
   facts='hyster/o (uterus) + -ectomy (removal). Removal of an ovary is an oophorectomy.'),
 C(lvl='medium', prog='CCMA', ans=['dys','men','rrhea'], tray=['dys','a','poly','men','rrhea','uria','pnea','algia','ia','phag','a_s','um'],
   text='A 16-year-old tells the medical assistant that she has severe cramps and pain every month during her period.',
   q='What is the medical term for painful periods?', say='dis-men-oh-REE-uh', body='Uterus · female reproductive system', kind='Symptom',
   facts='dys- (painful) + men/o (menstruation) + -rrhea (flow). Absent periods would be amenorrhea.'),
]
