# 12 new MedDecode Encounter patients (drafts for instructor review).
def F(t,lay,d,red=False): return {'t':t,'lay':lay,'d':d,'red':red}
def A(by,say,*f,**k):
    o={'by':by,'say':say}
    if f: o['f']=list(f)
    o.update(k); return o
def V(vit,abn,*f): return {'by':'Vital signs','say':'Recorded.','vit':vit,'abn':abn,**({'f':list(f)} if f else {})}

NEW = [
# ---------------- EMT ----------------
{'id':'E3','prog':'EMT','title':'Swollen lips after shrimp at dinner','cond':['Anaphylaxis'],'sys':['Immune','Respiratory'],'age':'Adult',
 'name':'Tasha Greene','ageText':'24-year-old woman','scene':'Restaurant dining room. A server called 911.',
 'open':[A('Tasha',"My throat feels tight... and I'm itchy all over.")],
 'dflt':A('Tasha',"No... I don't think so."),
 'a':{
  'cc':A('Tasha',"I ate some of my friend's pasta, and I think it had shrimp in it. Ten minutes later I broke out in hives, and now my lips are swelling.",F('Urticaria','hives','raised, itchy welts on the skin, often from an allergic reaction')),
  'allergies':A('Tasha',"Shellfish. I'm really allergic to shellfish.",F('Allergy: shellfish','allergic to shellfish','a known trigger for her reaction',True)),
  'events':A('Tasha',"Eating dinner. There must have been shrimp in the sauce."),
  'onset':A('Tasha',"About fifteen minutes ago, and it's getting worse fast.",F('Rapid onset, worsening','started 15 minutes ago, getting worse','reactions that progress quickly are more dangerous',True)),
  'breath':A('Tasha',"It's hard to breathe. I'm wheezing.",F('Dyspnea with wheezing','trouble breathing, wheezing','narrowed airways from the allergic reaction',True)),
  'swallow':A('Tasha',"It's hard to swallow. My throat feels like it's closing.",F('Throat tightness','throat feels like it is closing','swelling that can block the airway',True)),
  'swelling':A('Tasha',"My lips and tongue feel huge.",F('Angioedema','swelling of the lips and tongue','swelling deep under the skin, here around the mouth and airway',True)),
  'rash':A('Tasha',"I'm itching everywhere. Look at my arms.",F('Generalized urticaria','hives all over','hives spread across the body')),
  'meds':A('Tasha',"I have an EpiPen in my purse. I've never had to use it.",F('Prescribed epinephrine auto-injector','has an EpiPen','her own prescribed epinephrine',True)),
  'pmh':A('Tasha',"Just the shellfish allergy and a little asthma when I was a kid."),
  'dizzy':A('Tasha',"Yeah, kind of lightheaded."),
  'nausea':A('Tasha',"My stomach is cramping."),
  'lastmeal':A('Tasha',"The pasta, about fifteen minutes ago."),
  'prior':A('Tasha',"I got hives once as a kid, but never like this."),
  'vitals':V({'BP':'88/52','HR':'124','RR':'28','SpO2':'91%','Temp':'98.6°F'},['BP','HR','RR','SpO2'],F('Hypotension and tachycardia','low blood pressure, fast heart rate','signs of shock from a severe allergic reaction',True)),
  'skin':A('Skin check',"Flushed with raised hives on the arms, chest and neck. Lips visibly swollen."),
  'lungs':A('Lung sounds',"Wheezing heard in both lungs.",F('Bilateral wheezing','wheezing in both lungs','narrowed lower airways'))
 },
 'key':[['allergies','Ask about allergies','A known shellfish allergy plus exposure points straight to anaphylaxis.'],
        ['breath|lungs','Check breathing','Wheezing and trouble breathing mean the airway is involved.'],
        ['swallow|swelling','Ask about throat and swelling','Throat tightness and lip swelling can block the airway.'],
        ['meds','Ask about medications','Her own epinephrine auto-injector is the key treatment.'],
        ['vitals','Take vital signs','Low blood pressure and a fast pulse show shock.']],
 'end':{'q':'What is your field impression, and what is your next step?','opts':[
   ["Anaphylaxis. Give epinephrine by auto-injector per protocol, give high-flow oxygen, and transport rapidly while watching her airway.",True,"Hives, lip and tongue swelling, wheezing and low blood pressure after shellfish exposure is anaphylaxis. Epinephrine is the first-line treatment."],
   ["Mild allergic reaction. Give her something to drink and let her rest.",False,"Airway swelling, wheezing and low blood pressure make this life-threatening, not mild."],
   ["Asthma attack. Coach slow breathing and release her.",False,"Hives, swollen lips and low blood pressure point to anaphylaxis, not asthma alone."],
   ["Food poisoning. Transport non-emergently.",False,"Food poisoning doesn't cause hives, airway swelling or shock within minutes."]]},
 'chartIt':[["Raised, itchy welts on her skin.","Urticaria",["Urticaria","Erythema","Pruritus","Eczema"],"Urticaria means hives. Pruritus means itching; erythema means redness."],
            ["Her lips and tongue are swelling.","Angioedema",["Angioedema","Lymphedema","Hematoma","Emphysema"],"Angi (vessel) + -edema (swelling): swelling deep in the tissues."],
            ["A severe, whole-body allergic reaction.","Anaphylaxis",["Anaphylaxis","Asphyxia","Ataxia","Apnea"],"Anaphylaxis is a life-threatening allergic reaction."]]},

{'id':'E4','prog':'EMT','title':'Fall in the bathroom','cond':['Hip fracture'],'sys':['Skeletal'],'age':'Older adult',
 'name':'Margaret Ellis','ageText':'82-year-old woman','scene':'Her home. Her son found her on the bathroom floor and called 911.',
 'open':[A('Margaret',"Oh, my hip. Please don't move my leg.")],
 'dflt':A('Margaret',"No, not that I know of."),
 'a':{
  'cc':A('Margaret',"I slipped getting out of the tub and landed on my right side. My hip hurts terribly.",F('Fall with right hip pain','fell, right hip pain','a fall onto the hip in an older adult is a classic cause of hip fracture',True)),
  'events':A('Margaret',"I slipped on the wet floor. I didn't feel dizzy or anything before; I just slipped.",F('Mechanical fall','slipped, no dizziness before','a fall caused by slipping, not by fainting or illness')),
  'onset':A('Son',"She thinks it was about an hour ago. She couldn't get up to reach the phone."),
  'injury':A('Margaret',"No, I didn't hit my head. I landed on my hip and caught myself with my hand.",F('Denies head strike','did not hit her head','important, especially because she takes a blood thinner')),
  'region':A('Margaret',"Right here, my right hip and groin."),
  'severity':A('Margaret',"A nine. I can't move it."),
  'move':A('Margaret',"I can't lift my right leg at all. Please don't make me.",F('Unable to bear weight or lift the leg','can\'t move her right leg','a strong sign of a hip fracture',True)),
  'meds':A('Son',"She takes a blood thinner, apixaban, for an irregular heartbeat, and something for blood pressure.",F('Anticoagulant (apixaban)','takes a blood thinner','raises the risk of bleeding from injuries',True)),
  'pmh':A('Son',"Atrial fibrillation, high blood pressure and osteoporosis.",F('Osteoporosis','thin, weak bones','makes bones break more easily')),
  'dizzy':A('Margaret',"No, I'm not dizzy."),
  'allergies':A('Margaret',"Codeine makes me sick."),
  'lastmeal':A('Margaret',"Tea and toast around eight."),
  'legs':A('Observation',"The right leg is shorter than the left and turned outward. Bruising over the right hip. Pulse, feeling and movement in the right foot are present.",F('Shortened, externally rotated right leg','right leg shorter and turned out','the classic look of a hip fracture',True),F('Ecchymosis over the right hip','bruise on the hip','bleeding under the skin')),
  'vitals':V({'BP':'146/88','HR':'96 irreg','RR':'20','SpO2':'96%','Temp':'97.6°F'},['HR']),
  'skin':A('Skin check',"Pale and a little cool. Large bruise over the right hip.")
 },
 'key':[['events','Ask how she fell','A simple slip is different from fainting or a stroke.'],
        ['injury','Ask whether she hit her head','A head injury in someone on a blood thinner is dangerous.'],
        ['legs','Look at her legs','A shortened, turned-out leg is the classic sign of a hip fracture.'],
        ['meds','Ask about medications','Her blood thinner raises the risk of bleeding.'],
        ['move','Ask whether she can move her leg','She can\'t lift or bear weight on it.']],
 'end':{'q':'What is your field impression, and what is your next step?','opts':[
   ["Suspected right hip fracture. Immobilize the leg in the position of comfort, check pulse, movement and feeling in the foot, and transport. Report that she takes a blood thinner.",True,"A fall onto the hip, a shortened and turned-out leg and inability to move it point to a hip fracture."],
   ["Help her stand and walk to the stretcher.",False,"Never make a patient walk on a possible hip fracture."],
   ["Bruised hip. Advise ice and rest at home.",False,"The leg position and inability to move it point to a fracture, which needs the hospital."],
   ["Treat it as a stroke and transport to the stroke center.",False,"She slipped, had no dizziness, and shows no stroke signs."]]},
 'chartIt':[["A broken hip bone.","Fracture",["Fracture","Dislocation","Sprain","Contusion"],"A fracture is a broken bone. A dislocation is a joint out of place."],
            ["A large bruise over her hip.","Ecchymosis",["Ecchymosis","Erythema","Edema","Petechiae"],"Ecchymosis is a bruise: blood leaking under the skin."],
            ["She takes a blood thinner.","Anticoagulant",["Anticoagulant","Analgesic","Antibiotic","Antiemetic"],"Anti- (against) + coagul (clotting)."]]},

{'id':'E5','prog':'EMT','title':'Wheezing at football practice','cond':['Asthma'],'sys':['Respiratory'],'age':'Teen',
 'name':'Jordan Price','ageText':'16-year-old boy, with his coach','scene':'High school practice field. The athletic trainer called 911.',
 'open':[A('Jordan',"Can't... catch... my breath.")],
 'dflt':A('Coach',"Not that I've seen."),
 'a':{
  'cc':A('Coach',"He started wheezing during sprints about twenty minutes ago. It keeps getting worse.",F('Dyspnea with wheezing','trouble breathing, wheezing','narrowed airways',True)),
  'breath':A('Jordan',"Can't... finish... a sentence.",F('Speaks in 2–3 word phrases','can only say a few words at a time','a sign of a severe asthma attack',True)),
  'meds':A('Coach',"He has an albuterol inhaler. He used it twice, and it barely helped.",F('Rescue inhaler used twice without relief','inhaler not working','a severe attack that needs more treatment',True)),
  'pmh':A('Coach',"He has asthma. His mom said he was in the hospital for it last year.",F('Asthma; prior hospitalization','asthma, hospitalized before','a history that raises the risk of a severe attack')),
  'allergies':A('Jordan',"Pollen... cats."),
  'onset':A('Coach',"About twenty minutes ago, during sprints."),
  'events':A('Coach',"Running sprints. It's cold and the pollen count is high today."),
  'chest':A('Jordan',"Tight... not pain."),
  'cough':A('Jordan',"Yeah... coughing."),
  'prior':A('Coach',"He's had attacks before, but I've never seen one this bad."),
  'lungs':A('Lung sounds',"Loud wheezing in both lungs; air movement is reduced at the bases.",F('Diffuse wheezing, decreased air movement','wheezing, little air moving','a severe narrowing of the airways',True)),
  'vitals':V({'BP':'132/80','HR':'128','RR':'32','SpO2':'89%','Temp':'98.4°F'},['HR','RR','SpO2'],F('Tachypnea and low oxygen saturation','fast breathing, oxygen 89%','his body isn\'t getting enough oxygen',True)),
  'skin':A('Skin check',"Sweaty. He is using his neck and chest muscles to breathe.",F('Accessory muscle use','using neck muscles to breathe','extra effort to move air; a sign of respiratory distress',True))
 },
 'key':[['breath','Check how well he can talk and breathe','Speaking only a few words is a sign of a severe attack.'],
        ['meds','Ask about his inhaler','Two puffs without relief means the attack is severe.'],
        ['pmh','Ask about medical history','Past hospitalization for asthma raises the risk.'],
        ['lungs','Listen to lung sounds','Wheezing with little air movement is serious.'],
        ['vitals','Take vital signs','Oxygen at 89% and fast breathing need treatment now.']],
 'end':{'q':'What is your field impression, and what is your next step?','opts':[
   ["Severe asthma attack. Sit him upright, give oxygen, assist with his prescribed inhaler per protocol, and transport rapidly.",True,"Wheezing, short phrases, low oxygen and an inhaler that isn't working are a severe asthma attack."],
   ["Exercise fatigue. Have him rest on the bench and drink water.",False,"Low oxygen and an inhaler that isn't working make this an emergency."],
   ["Panic attack. Coach slow breathing into a paper bag.",False,"Never use a paper bag. His wheezing and low oxygen point to asthma."],
   ["Have him lie flat and rest until his breathing settles.",False,"Lying flat makes breathing harder. Keep him upright."]]},
 'chartIt':[["He is breathing 32 times a minute.","Tachypnea",["Tachypnea","Bradypnea","Apnea","Orthopnea"],"Tachy- (fast) + -pnea (breathing)."],
            ["A sudden worsening of his asthma.","Exacerbation",["Exacerbation","Remission","Relapse","Prognosis"],"An exacerbation is a flare-up of a chronic condition."],
            ["His airway muscles are tightening.","Bronchospasm",["Bronchospasm","Bronchitis","Bronchiectasis","Pneumothorax"],"Bronch (airway) + -spasm (sudden tightening)."]]},

# ---------------- CNA ----------------
{'id':'C3','prog':'CNA','title':'Found on the floor by the bed','cond':['Fall','Head injury'],'sys':['Skeletal','Nervous'],'age':'Older adult',
 'name':'Frank Moreno','ageText':'78-year-old man','scene':'Long-term care, early morning. You find him sitting on the floor beside his bed.',
 'open':[A('Frank',"Well, this is embarrassing. Help me up, would you?")],
 'dflt':A('Frank',"No, I'm fine. Just help me up."),
 'a':{
  'cc':A('Frank',"I was trying to get to the bathroom and my feet slid out from under me.",F('Unwitnessed fall','fell while alone','falls nobody saw must always be reported',True)),
  'events':A('Frank',"I didn't want to wait for help. I really had to go.",F('Fall while toileting without help','tried to walk to the bathroom alone','a common cause of falls')),
  'injury':A('Frank',"I bumped my head on the nightstand, I think. And my left wrist hurts.",F('Head strike','hit his head','a head injury must be reported, especially with a blood thinner',True)),
  'pain':A('Frank',"My left wrist. It hurts to move it.",F('Left wrist pain','wrist hurts','a possible fracture')),
  'move':A('Frank',"I can wiggle my fingers, but turning the wrist hurts a lot."),
  'dizzy':A('Frank',"A little woozy, but that might be from getting up too fast."),
  'headache':A('Frank',"My head's a bit sore where I bumped it."),
  'normal':A('Night-shift aide',"He's usually alert and walks with a walker. He's supposed to call for help at night."),
  'meds':A('Night-shift aide',"I know he's on warfarin. The nurse has the full list.",F('Anticoagulant (warfarin)','takes a blood thinner','raises the risk of bleeding inside the head after a fall',True)),
  'bleeding':A('Observation',"A small cut on his forehead with a little bleeding.",F('Laceration on the forehead','small cut on the forehead','a cut in the skin')),
  'skin':A('Skin check',"Small cut and a bump on the left forehead. Left wrist is swollen.",F('Contusion on the forehead','bump on the head','a bruise from a blow')),
  'vitals':V({'BP':'138/84','HR':'88','RR':'18','SpO2':'97%','Temp':'98.0°F'},[])
 },
 'key':[['cc|events','Ask what happened','Knowing how he fell helps the nurse and prevents the next fall.'],
        ['injury','Ask whether he hit his head','A head injury must be reported right away.'],
        ['meds','Find out about blood thinners','A blood thinner makes a head bump much more serious.'],
        ['pain|move','Ask where it hurts','His wrist may be broken.'],
        ['skin|bleeding','Look for cuts and bruises','The nurse needs to know every injury.']],
 'end':{'q':'You are the CNA. What do you do now?','opts':[
   ["Don't move him. Stay with him and call the nurse right away. Report that he hit his head, has a cut on his forehead and a painful wrist, takes a blood thinner, and was walking to the bathroom alone.",True,"After a fall, the nurse must assess the resident before anyone moves him. A head strike in someone on a blood thinner is urgent."],
   ["Help him back into bed, then tell the nurse at the end of your shift.",False,"Moving him could worsen an injury, and a fall must be reported right away."],
   ["Put ice on his wrist and let him rest on the floor.",False,"Treatment decisions come from the nurse. Call the nurse first."],
   ["Clean the cut, put on a bandage, and help him to the bathroom.",False,"He needs a nurse's assessment before he moves anywhere."]]},
 'chartIt':[["A small cut on his forehead.","Laceration",["Laceration","Abrasion","Contusion","Avulsion"],"A laceration is a cut. An abrasion is a scrape."],
            ["A bump and bruise on his head.","Contusion",["Contusion","Concussion","Hematuria","Lesion"],"A contusion is a bruise. A concussion is a brain injury."],
            ["He takes warfarin.","Anticoagulant",["Anticoagulant","Antipyretic","Antibiotic","Anticonvulsant"],"A medicine that slows blood clotting."]]},

{'id':'C4','prog':'CNA','title':'Not drinking much lately','cond':['Dehydration'],'sys':['Urinary','Cardiovascular'],'age':'Older adult',
 'name':'Ruth Anderson','ageText':'88-year-old woman','scene':'Long-term care, afternoon. You are helping her back to bed after lunch.',
 'open':[A('Ruth',"Oh, the room is spinning a little when I stand up.")],
 'dflt':A('Ruth',"I don't think so, dear."),
 'a':{
  'cc':A('Ruth',"I feel weak and dizzy when I stand. My mouth is so dry.",F('Orthostatic dizziness','dizzy when standing up','dizziness when blood pressure drops on standing',True)),
  'dizzy':A('Ruth',"Only when I stand up. It goes away when I sit.",F('Orthostatic dizziness','dizzy when standing up','dizziness when blood pressure drops on standing',True)),
  'lastmeal':A('Day-shift aide',"She's only drinking a few sips for the last two days. Her lunch tray came back almost full.",F('Decreased fluid and food intake','drinking and eating very little','the main cause of dehydration in older adults',True)),
  'thirst':A('Ruth',"My mouth feels like cotton.",F('Xerostomia','dry mouth','xer/o (dry) + stom (mouth); a sign of dehydration')),
  'urine':A('Ruth',"I don't need to go much at all."),
  'urinecheck':A('Observation',"Only about 80 mL of dark amber urine in the bedpan since morning, with a strong smell.",F('Oliguria with concentrated urine','very little, dark urine','olig- (scanty) + -uria; the body is saving water',True)),
  'normal':A('Day-shift aide',"She's usually chatty and walks to the dining room. The last two days she's been tired and sleepy."),
  'weigh':A('Scale',"Today: 118 lb. Three days ago: 121 lb.",F('Weight loss 3 lb in 3 days','lost 3 pounds','rapid weight loss is usually fluid loss')),
  'fever':A('Ruth',"No, I'm not hot."),
  'skin':A('Skin check',"Lips and tongue dry and sticky. Skin on the back of her hand stays tented for a few seconds after a gentle pinch.",F('Poor skin turgor','skin stays tented','skin that is slow to flatten is a sign of dehydration')),
  'meds':A('Day-shift aide',"The nurse would know. I think she takes a water pill."),
  'vitals':V({'BP':'98/60','HR':'104','RR':'18','SpO2':'96%','Temp':'98.8°F'},['BP','HR'],F('Hypotension and tachycardia','low blood pressure, fast pulse','the heart speeds up to make up for low fluid volume',True))
 },
 'key':[['lastmeal','Ask about eating and drinking','Low intake for two days is the cause.'],
        ['urinecheck|urine','Check her urine output','Little, dark urine shows dehydration.'],
        ['dizzy|cc','Ask about dizziness','Dizziness on standing means she could fall.'],
        ['vitals','Take vital signs','Low blood pressure and a fast pulse must be reported.'],
        ['normal','Ask whether this is normal for her','New tiredness is a change from her usual self.']],
 'end':{'q':'You are the CNA. What do you do now?','opts':[
   ["Report to the nurse promptly: very little drinking for two days, small amount of dark urine, dry mouth, dizziness on standing, BP 98/60 and pulse 104. Keep her safe from falls and offer fluids if the nurse allows.",True,"These are signs of dehydration. The nurse needs every finding, and she needs fall precautions."],
   ["Encourage her to walk to the dining room to get her strength back.",False,"Dizziness on standing puts her at high risk of falling."],
   ["Write it in your notes; older adults don't drink much.",False,"Low intake with these changes is a problem to report, not to accept."],
   ["Skip her water pill today.",False,"Medication decisions belong to the nurse and provider."]]},
 'chartIt':[["She produced very little urine.","Oliguria",["Oliguria","Anuria","Polyuria","Dysuria"],"Olig- (scanty) + -uria. Anuria means no urine at all."],
            ["Her mouth is very dry.","Xerostomia",["Xerostomia","Stomatitis","Dysphagia","Halitosis"],"Xer/o (dry) + stom (mouth) + -ia."],
            ["Her body has lost too much fluid.","Dehydration",["Dehydration","Edema","Diuresis","Hydration"],"De- (removal) + hydr (water) + -ation."]]},

{'id':'C5','prog':'CNA','title':'A red spot that won\'t fade','cond':['Pressure injury'],'sys':['Integumentary'],'age':'Older adult',
 'name':'Helen Brooks','ageText':'91-year-old woman','scene':'Long-term care. She spends most of the day in bed after a stroke. You are giving morning care.',
 'open':[A('Helen',"My bottom is sore, honey.")],
 'dflt':A('Helen',"Not that I know of."),
 'a':{
  'cc':A('Helen',"It's sore right at my tailbone. It burns.",F('Sacral pain','sore tailbone','pain over the sacrum, a common spot for pressure injuries')),
  'skin':A('Skin check',"A red area about the size of a half-dollar over her tailbone (sacrum). It stays red when you press it gently and let go. The skin is not broken. The area is warm.",F('Non-blanchable erythema over the sacrum','red spot that doesn\'t fade when pressed','redness that stays when pressed is an early pressure injury',True),F('Intact skin','skin not broken','the skin is still closed')),
  'pain':A('Helen',"Mostly when I'm on my back."),
  'normal':A('Night-shift aide',"She needs help to turn. I turned her at two, but she was on her back for a long stretch before that.",F('Long time in one position','on her back a long time','pressure over bony areas causes skin breakdown',True)),
  'urine':A('Night-shift aide',"She wears a brief. She was wet when I changed her this morning.",F('Incontinence','wet brief','moisture weakens skin and raises the risk of breakdown')),
  'lastmeal':A('Helen',"I don't feel like eating much. A few bites."),
  'weight':A('Night-shift aide',"I think she's lost some weight this month."),
  'fever':A('Helen',"No."),
  'move':A('Helen',"I can't roll over by myself since my stroke.",F('Immobility','can\'t turn herself','a major risk factor for pressure injuries',True)),
  'vitals':V({'BP':'124/76','HR':'78','RR':'16','SpO2':'97%','Temp':'98.2°F'},[])
 },
 'key':[['skin','Look at the skin','A red area that doesn\'t fade when pressed is an early pressure injury.'],
        ['normal','Ask about positioning and turning','Too long in one position caused the pressure.'],
        ['urine','Ask about incontinence','Moisture makes skin break down faster.'],
        ['move','Ask whether she can move herself','She can\'t turn without help.'],
        ['cc|pain','Ask where it hurts','Pain over a bony area is a warning sign.']],
 'end':{'q':'You are the CNA. What do you do now?','opts':[
   ["Report the red area over her tailbone that doesn't fade when pressed. Keep pressure off it by repositioning her on schedule, keep her skin clean and dry, and don't massage the area.",True,"Non-blanchable redness is an early pressure injury. Relieving pressure and keeping skin dry helps stop it from opening."],
   ["Massage the red area with lotion to bring back circulation.",False,"Massaging a reddened bony area can damage the tissue further."],
   ["Put her back on her back with a pillow under her knees; it's just a little red.",False,"More pressure on the area will make it worse. It needs to be reported."],
   ["Wait and report it only if the skin breaks open.",False,"Catching it before the skin opens is the goal. Report it now."]]},
 'chartIt':[["Redness of the skin.","Erythema",["Erythema","Edema","Eczema","Ecchymosis"],"Erythr (red) + -ema: redness of the skin."],
            ["Skin damage from staying in one position.","Pressure injury",["Pressure injury","Abrasion","Laceration","Contusion"],"Also called a pressure ulcer, bedsore or decubitus ulcer."],
            ["She can't control her bladder.","Incontinence",["Incontinence","Retention","Dysuria","Frequency"],"Incontinence is the inability to control urine or stool."]]},

# ---------------- CCMA ----------------
{'id':'M3','prog':'CCMA','title':'Thirsty all the time','cond':['Diabetes','Hyperglycemia'],'sys':['Endocrine'],'age':'Adult',
 'name':'Derek Collins','ageText':'47-year-old man','scene':'Family medicine clinic, diabetes follow-up. You are rooming him.',
 'open':[A('Derek',"Hi. I've been feeling kind of run down.")],
 'dflt':A('Derek',"No, not really."),
 'a':{
  'cc':A('Derek',"I'm tired all the time, and I'm so thirsty. I keep a jug of water with me.",F('Polydipsia','extreme thirst','poly- (much) + -dipsia (thirst)',True)),
  'thirst':A('Derek',"I drink probably a gallon a day and I'm still thirsty.",F('Polydipsia','extreme thirst','poly- (much) + -dipsia (thirst)',True)),
  'urine':A('Derek',"I'm up three or four times a night to urinate. It's a lot every time.",F('Polyuria and nocturia','urinating a lot, waking at night to urinate','large amounts of urine, including at night',True)),
  'vision':A('Derek',"Things have been a little blurry the last couple weeks.",F('Blurred vision','blurry vision','high blood sugar can change the shape of the lens')),
  'weight':A('Derek',"I've actually lost about ten pounds without trying."),
  'meds':A('Derek',"Metformin, twice a day."),
  'missedmeds':A('Derek',"Honestly, I've been forgetting the evening dose a lot.",F('Missed doses of metformin','forgets evening dose','not taking medicine as prescribed')),
  'pmh':A('Derek',"Type 2 diabetes, about four years now. High cholesterol too."),
  'lastmeal':A('Derek',"A bagel and orange juice about an hour ago."),
  'allergies':A('Derek',"No allergies."),
  'onset':A('Derek',"Maybe the last three weeks it's gotten worse."),
  'dizzy':A('Derek',"No."),
  'nausea':A('Derek',"No vomiting."),
  'glucose':A('Glucometer',"Fingerstick blood glucose: 285 mg/dL (high).",F('Hyperglycemia, 285 mg/dL','high blood sugar','well above the normal range',True)),
  'vitals':V({'BP':'134/84','HR':'86','RR':'16','SpO2':'98%','Temp':'98.4°F'},[])
 },
 'key':[['thirst|cc','Ask about thirst','Extreme thirst is a sign of high blood sugar.'],
        ['urine','Ask about urination','Large amounts of urine are another key sign.'],
        ['missedmeds','Ask about missed medication','Missed doses help explain the high sugar.'],
        ['glucose','Check blood glucose (if ordered)','A reading of 285 confirms high blood sugar.'],
        ['vision','Ask about vision changes','Blurred vision is a symptom the provider needs to know.']],
 'end':{'q':'Which chart note should you enter for the provider?','opts':[
   ["CC: fatigue. Reports polydipsia, polyuria with nocturia x 3 weeks, blurred vision, unintended 10-lb weight loss; often misses evening metformin. Fingerstick glucose 285 mg/dL (ate 1 hr ago). Provider notified.",True,"Accurate terms, the timing of his last meal, the missed doses, and a prompt notice to the provider."],
   ["Patient's diabetes is out of control. Increase his metformin.",False,"Medical assistants don't diagnose or change medications."],
   ["CC: tired. Glucose high. No other complaints.",False,"This leaves out the thirst, urination, vision, weight loss and missed doses."],
   ["CC: fatigue. Glucose 285. Patient told to skip lunch to bring his sugar down.",False,"Giving treatment advice is outside a medical assistant's role."]]},
 'chartIt':[["He's thirsty all the time.","Polydipsia",["Polydipsia","Polyuria","Polyphagia","Dysphagia"],"Poly- (much) + -dipsia (thirst). Polyphagia is excessive hunger."],
            ["He gets up at night to urinate.","Nocturia",["Nocturia","Enuresis","Hematuria","Oliguria"],"Noct (night) + -uria (urine)."],
            ["His blood sugar is 285 mg/dL.","Hyperglycemia",["Hyperglycemia","Hypoglycemia","Glycosuria","Hypertension"],"Hyper- (above normal) + glyc (sugar) + -emia."]]},

{'id':'M4','prog':'CCMA','title':'Rolled ankle at basketball','cond':['Ankle sprain'],'sys':['Skeletal'],'age':'Teen',
 'name':'Marcus Hill','ageText':'17-year-old boy, with his father','scene':'Urgent care clinic. You are rooming him for the provider.',
 'open':[A('Marcus',"I rolled my ankle at practice. It's killing me.")],
 'dflt':A('Marcus',"Nope."),
 'a':{
  'cc':A('Marcus',"I came down on someone's foot after a rebound and my right ankle rolled in.",F('Inversion injury, right ankle','ankle rolled inward','the most common way ankles are sprained')),
  'events':A('Marcus',"Landing from a jump. I heard a pop.",F('Heard a pop','heard a pop','can mean a torn ligament or a fracture',True)),
  'onset':A('Dad',"About two hours ago."),
  'region':A('Marcus',"On the outside of my ankle, right below the bone."),
  'swelling':A('Marcus',"It swelled up like a tennis ball.",F('Edema, right lateral ankle','swollen ankle','swelling from fluid in the tissues')),
  'move':A('Marcus',"I could take a few steps limping, but it really hurts to put weight on it.",F('Able to bear weight with pain','can limp a few steps','one of the questions the provider uses to decide on an X-ray')),
  'pain':A('Marcus',"It's a 7. Worse when I move it."),
  'severity':A('Marcus',"A 7 out of 10."),
  'prior':A('Marcus',"I sprained the same ankle last season."),
  'meds':A('Dad',"He took ibuprofen at practice about an hour ago.",F('Ibuprofen 1 hour ago','took ibuprofen','the provider needs the time of the last dose')),
  'allergies':A('Dad',"No allergies."),
  'skin':A('Observation',"Swelling and purple bruising on the outside of the right ankle. Toes are warm and pink.",F('Ecchymosis, right ankle','bruising','blood under the skin from the injury'),F('Good circulation to the toes','toes warm and pink','circulation below the injury is normal')),
  'injury':A('Marcus',"No, just my ankle."),
  'vitals':V({'BP':'122/74','HR':'84','RR':'16','SpO2':'99%','Temp':'98.6°F'},[])
 },
 'key':[['cc|events','Ask how it happened','The way it rolled and the pop matter to the provider.'],
        ['move','Ask whether he can bear weight','Bearing weight helps the provider decide on an X-ray.'],
        ['swelling|skin','Check for swelling and bruising','Document what you see.'],
        ['meds','Ask about medication taken','Ibuprofen may mask pain; the time matters.'],
        ['prior','Ask about past injuries','A repeat sprain changes the plan.']],
 'end':{'q':'Which chart note should you enter for the provider?','opts':[
   ["CC: right ankle injury x 2 hrs. Inversion injury landing from a jump; heard a pop. Swelling and ecchymosis of the lateral ankle; able to bear weight with pain; toes warm and pink. Pain 7/10. Ibuprofen 1 hr ago. Prior sprain same ankle. NKDA.",True,"Complete and accurate, using the right terms, including how it happened, weight bearing and circulation."],
   ["Patient has a sprained ankle. Wrap it and send him home.",False,"Medical assistants don't diagnose or decide treatment."],
   ["CC: ankle pain. Patient fine.",False,"This leaves out how it happened, the swelling, weight bearing and medication."],
   ["CC: right ankle fracture. Needs a cast.",False,"Only the provider can diagnose a fracture, usually after an X-ray."]]},
 'chartIt':[["His ankle is swollen.","Edema",["Edema","Erythema","Ecchymosis","Emphysema"],"Edema is swelling from fluid in the tissues."],
            ["Purple bruising on his ankle.","Ecchymosis",["Ecchymosis","Petechiae","Hematoma","Cyanosis"],"Ecchymosis is a bruise."],
            ["A stretched or torn ligament.","Sprain",["Sprain","Strain","Fracture","Dislocation"],"A sprain injures a ligament; a strain injures a muscle or tendon."]]},

{'id':'M5','prog':'CCMA','title':'Chest pressure in the waiting room','cond':['Heart attack'],'sys':['Cardiovascular'],'age':'Adult',
 'name':'Walter Kim','ageText':'62-year-old man','scene':'Family medicine clinic. He came in for a medication refill. You are rooming him.',
 'open':[A('Walter',"Sorry, I'm a little out of breath. The walk from the parking lot got to me.")],
 'dflt':A('Walter',"No, nothing like that."),
 'a':{
  'cc':A('Walter',"I'm just here for my refills. But I've had this pressure in my chest since I walked in from the parking lot.",F('Chest pressure','pressure in the chest','a possible sign of a heart attack',True)),
  'chest':A('Walter',"It's like a tight band across my chest. It hasn't let up.",F('Persistent chest pressure','tight band across the chest','chest pressure that doesn\'t go away is an emergency sign',True)),
  'onset':A('Walter',"About twenty minutes ago.",F('Onset 20 minutes ago','started 20 minutes ago','ongoing for 20 minutes',True)),
  'region':A('Walter',"Mostly the middle, and my left shoulder aches too."),
  'breath':A('Walter',"I can't quite get a full breath.",F('Dyspnea','short of breath','difficult breathing')),
  'sweat':A('Walter',"Yeah, I'm sweating, and it's cool in here.",F('Diaphoresis','sweating','profuse sweating',True)),
  'nausea':A('Walter',"A little queasy."),
  'prov':A('Walter',"Sitting down hasn't helped."),
  'pmh':A('Walter',"High blood pressure and high cholesterol. My dad had a heart attack at 60."),
  'meds':A('Walter',"Lisinopril and atorvastatin. That's what I need refilled."),
  'allergies':A('Walter',"No allergies."),
  'vitals':V({'BP':'162/96','HR':'108','RR':'22','SpO2':'94%','Temp':'98.2°F'},['BP','HR','RR'],F('Tachycardia and hypertension','fast pulse, high blood pressure','abnormal vital signs with chest pressure',True)),
  'skin':A('Skin check',"Pale and sweaty.")
 },
 'key':[['cc|chest','Ask about the chest pressure','Chest pressure that won\'t go away is an emergency.'],
        ['onset','Ask when it started','Twenty minutes of pressure is serious.'],
        ['sweat','Ask about sweating','Sweating with chest pressure raises concern.'],
        ['breath','Ask about breathing','Shortness of breath adds to the concern.'],
        ['vitals','Take vital signs','A fast pulse and high blood pressure confirm the urgency.']],
 'end':{'q':'What do you do?','opts':[
   ["Stop rooming. Stay with him, alert the provider immediately, and follow the clinic's emergency protocol (including calling 911). Report: chest pressure for 20 minutes not relieved by rest, sweating, shortness of breath, HR 108, BP 162/96.",True,"Possible heart attack. In a clinic, the medical assistant's job is to recognize it, get the provider right away and follow the emergency protocol."],
   ["Finish rooming and let the provider see him in turn.",False,"Chest pressure with sweating and shortness of breath can't wait in line."],
   ["Tell him to drive to the emergency room.",False,"A person with possible heart attack symptoms should never drive himself."],
   ["Give him one of the clinic's aspirin and have him rest.",False,"Medical assistants don't give medication without a provider's order. Get the provider now."]]},
 'chartIt':[["He is sweating heavily.","Diaphoresis",["Diaphoresis","Diuresis","Dyspnea","Dysphoria"],"Diaphoresis means profuse sweating."],
            ["He's short of breath.","Dyspnea",["Dyspnea","Apnea","Orthopnea","Tachypnea"],"Dys- (difficult) + -pnea (breathing)."],
            ["His heart rate is 108.","Tachycardia",["Tachycardia","Bradycardia","Arrhythmia","Palpitations"],"Tachy- (fast) + cardi (heart) + -ia."]]},

# ---------------- Dental ----------------
{'id':'D3','prog':'Dental','title':'Bleeding gums and a loose tooth','cond':['Periodontitis'],'sys':['Oral'],'age':'Adult',
 'name':'Gary Lowe','ageText':'56-year-old man','scene':'Dental office, new-patient visit. You are taking his history before the hygienist begins.',
 'open':[A('Gary',"My gums bleed every time I brush, and one of my bottom teeth feels loose.")],
 'dflt':A('Gary',"No, I don't think so."),
 'a':{
  'cc':A('Gary',"My gums bleed when I brush, and a lower front tooth wiggles.",F('Gingival bleeding','bleeding gums','a sign of gum inflammation'),F('Tooth mobility','loose tooth','loss of the bone that holds the tooth',True)),
  'taste':A('Gary',"My wife says my breath is bad, even right after I brush.",F('Halitosis','bad breath','often caused by gum disease')),
  'lastdental':A('Gary',"Probably eight years.",F('No dental care in 8 years','last visit 8 years ago','plaque and tartar build up without cleanings')),
  'social':A('Gary',"About a pack a day for thirty years.",F('Tobacco use','smokes a pack a day','a major risk factor for gum disease',True)),
  'pmh':A('Gary',"Type 2 diabetes. My last A1C was high.",F('Type 2 diabetes, poorly controlled','diabetes, sugar not well controlled','diabetes and gum disease make each other worse',True)),
  'meds':A('Gary',"Metformin. And I take a baby aspirin every day.",F('Daily aspirin','takes aspirin daily','can increase bleeding during treatment')),
  'pain':A('Gary',"Not much pain, just sore gums sometimes."),
  'swelling':A('Gary',"My gums look puffy."),
  'allergies':A('Gary',"No allergies."),
  'onset':A('Gary',"The bleeding has been going on for a year or two. The loose tooth is new this month."),
  'mouth':A('Observation',"Red, swollen gums that bleed when touched. Gums have pulled back from several teeth. Heavy tartar. The lower left central incisor moves slightly. Deep pockets between gums and teeth (6 mm in several spots).",F('Gingival recession','gums pulled back','exposes the root and is a sign of bone loss'),F('Periodontal pockets 6 mm','deep gum pockets','deep spaces between gum and tooth show bone loss',True)),
  'vitals':V({'BP':'144/90','HR':'80','RR':'16','SpO2':'97%','Temp':'98.4°F'},['BP'])
 },
 'key':[['cc','Ask about his main concern','Bleeding gums and a loose tooth are warning signs.'],
        ['mouth','Look in the mouth','Deep pockets and recession show bone loss.'],
        ['social','Ask about smoking','Smoking is a major risk factor.'],
        ['pmh','Ask about medical conditions','Diabetes and gum disease worsen each other.'],
        ['meds','Ask about medications','Daily aspirin can increase bleeding during treatment.']],
 'end':{'q':'What do you tell the dentist?','opts':[
   ["Signs of advanced gum disease: bleeding, puffy gums, recession, 6 mm pockets, a loose lower incisor and bad breath. No dental care in 8 years. Smokes a pack a day, has poorly controlled type 2 diabetes, and takes daily aspirin.",True,"These findings point to periodontitis. Smoking, diabetes and aspirin all affect the treatment plan."],
   ["Gingivitis only. Schedule a regular cleaning.",False,"Deep pockets, recession and a loose tooth mean bone loss, which is periodontitis, not just gingivitis."],
   ["Pull the loose tooth today.",False,"Treatment decisions belong to the dentist after a full exam."],
   ["Normal for his age. No changes needed.",False,"Bleeding gums and a loose tooth are never just normal aging."]]},
 'chartIt':[["His breath smells bad.","Halitosis",["Halitosis","Xerostomia","Stomatitis","Gingivitis"],"Halit (breath) + -osis (abnormal condition)."],
            ["Infection that has destroyed bone around the teeth.","Periodontitis",["Periodontitis","Gingivitis","Pulpitis","Glossitis"],"Peri- (around) + odont (tooth) + -itis."],
            ["His gums have pulled back from the teeth.","Gingival recession",["Gingival recession","Gingival hyperplasia","Abscess","Caries"],"Recession exposes the tooth root."]]},

{'id':'D4','prog':'Dental','title':'Fainting during the injection','cond':['Syncope'],'sys':['Cardiovascular','Nervous'],'age':'Adult',
 'name':'Emily Shaw','ageText':'29-year-old woman','scene':'Dental office. The dentist just gave a numbing injection, and she suddenly went pale and slumped in the chair for a few seconds.',
 'open':[A('Emily',"What... what happened? I feel awful.")],
 'dflt':A('Emily',"No... I don't think so."),
 'a':{
  'cc':A('Emily',"I saw the needle and everything went gray. I feel sweaty and sick.",F('Brief loss of consciousness','fainted for a few seconds','a short loss of consciousness',True)),
  'events':A('Emily',"I'm terrified of needles. I didn't sleep last night worrying about this.",F('Needle fear and anxiety','very afraid of needles','a common trigger for fainting')),
  'lastmeal':A('Emily',"I skipped breakfast. I was too nervous to eat."),
  'nausea':A('Emily',"Yes, a little queasy."),
  'sweat':A('Emily',"I'm clammy.",F('Diaphoresis','sweaty, clammy','profuse sweating')),
  'dizzy':A('Emily',"Still a little lightheaded, but better now that I'm lying back."),
  'prior':A('Emily',"I fainted once when I got blood drawn in high school.",F('Previous fainting with needles','fainted before with a blood draw','supports a common, harmless type of fainting')),
  'chest':A('Emily',"No chest pain."),
  'breath':A('Emily',"I can breathe fine."),
  'pmh':A('Emily',"I'm healthy. No heart problems."),
  'meds':A('Emily',"Just birth control pills."),
  'allergies':A('Emily',"No allergies."),
  'injury':A('Dental assistant',"She stayed in the chair and didn't hit anything."),
  'glucose':A('Office glucometer',"Blood glucose: 102 mg/dL (normal).",F('Normal blood glucose','blood sugar normal','low blood sugar is not the cause')),
  'vitals':V({'BP':'88/56','HR':'52','RR':'16','SpO2':'98%','Temp':'98.2°F'},['BP','HR'],F('Hypotension and bradycardia','low blood pressure, slow pulse','typical of a common fainting reaction',True)),
  'skin':A('Skin check',"Pale, cool and sweaty. Color returning since she was laid back.")
 },
 'key':[['cc','Ask what she felt','Seeing the needle and going gray points to a fainting reaction.'],
        ['events','Ask what led up to it','Fear of needles is a common trigger.'],
        ['vitals','Take vital signs','Low blood pressure and a slow pulse fit fainting.'],
        ['glucose','Check blood glucose','Rules out low blood sugar.'],
        ['chest|breath','Ask about chest pain or breathing','Their absence makes a heart problem less likely.']],
 'end':{'q':'What do you do?','opts':[
   ["Stop treatment and alert the dentist. Lay her back with her legs raised, loosen anything tight, monitor her breathing and vital signs, and give oxygen if your office protocol calls for it. She most likely fainted from fear.",True,"This is a common fainting reaction (vasovagal syncope). Lying flat with legs up restores blood flow to the brain."],
   ["Sit her straight up and continue the procedure.",False,"Sitting up can make her faint again. Keep her lying back with legs raised until she recovers."],
   ["Give her the rest of the anesthetic so the procedure can finish.",False,"Stop treatment until she has fully recovered and the dentist decides."],
   ["Call 911 immediately.",False,"She is recovering, breathing normally, and her blood sugar is normal. Follow office protocol; call 911 if she doesn't recover or gets worse."]]},
 'chartIt':[["She fainted briefly.","Syncope",["Syncope","Seizure","Vertigo","Coma"],"Syncope is a brief loss of consciousness from reduced blood flow to the brain."],
            ["Her pulse is 52.","Bradycardia",["Bradycardia","Tachycardia","Arrhythmia","Hypotension"],"Brady- (slow) + cardi (heart) + -ia."],
            ["Her blood pressure is 88/56.","Hypotension",["Hypotension","Hypertension","Hypoglycemia","Hypoxia"],"Hypo- (below normal) + tension (pressure)."]]},

{'id':'D5','prog':'Dental','title':'Knocked-out front tooth','cond':['Tooth avulsion'],'sys':['Oral'],'age':'Child',
 'name':'Ava Martinez','ageText':'9-year-old girl, with her mother','scene':'Dental office, emergency walk-in. She fell off her bike 20 minutes ago.',
 'open':[A('Mom',"She fell off her bike and her front tooth came out! I have it here in a napkin.")],
 'dflt':A('Mom',"No, I don't think so."),
 'a':{
  'cc':A('Ava',"My front tooth came out when I hit the sidewalk.",F('Avulsed permanent tooth','tooth knocked out completely','a dental emergency; the sooner it is put back, the better',True)),
  'onset':A('Mom',"About twenty minutes ago.",F('Out of the mouth about 20 minutes','20 minutes ago','time outside the mouth decides whether the tooth can be saved',True)),
  'tooth':A('Mom',"It's wrapped in a napkin. It was dry. I rinsed it under the tap and scrubbed off the dirt.",F('Tooth stored dry; root scrubbed','kept dry in a napkin, scrubbed','drying and scrubbing damage the cells on the root that help it reattach',True)),
  'events':A('Ava',"I hit a rock and flew over the handlebars."),
  'injury':A('Mom',"She had her helmet on. She didn't pass out.",F('Helmet on; no loss of consciousness','no passing out','important to check for a head injury')),
  'headache':A('Ava',"No, my head doesn't hurt."),
  'dizzy':A('Ava',"No."),
  'nausea':A('Ava',"No, I didn't throw up.",F('No vomiting','no vomiting','vomiting after a fall can signal a head injury')),
  'bleeding':A('Mom',"Her mouth was bleeding a lot, but it's slowing down."),
  'lastdental':A('Mom',"She had a checkup three months ago."),
  'pmh':A('Mom',"She's healthy."),
  'meds':A('Mom',"None."),
  'allergies':A('Mom',"No allergies."),
  'mouth':A('Observation',"The upper left front permanent tooth is missing; the socket has a clot and is oozing slightly. Small cut on the inside of the upper lip.",F('Empty socket, upper left central incisor','missing front tooth','where the tooth came from'),F('Laceration of the upper lip','cut inside the lip','a cut in the soft tissue')),
  'vitals':V({'BP':'104/66','HR':'98','RR':'20','SpO2':'99%','Temp':'98.6°F'},[])
 },
 'key':[['onset','Ask when it happened','Time outside the mouth decides whether the tooth can be saved.'],
        ['tooth','Ask where the tooth is and how it was kept','How the tooth was stored affects the outcome.'],
        ['injury|nausea|headache','Check for a head injury','A fall hard enough to knock out a tooth can hurt the head too.'],
        ['mouth','Look in the mouth','Confirm which tooth and check for other injuries.'],
        ['cc','Ask what happened','A permanent tooth needs emergency care.']],
 'end':{'q':'What do you do?','opts':[
   ["Alert the dentist right away; this is a time-critical emergency. Handle the tooth only by the crown, don't scrub it, and keep it moist in milk or saline (or a tooth-preservation kit). Tell the dentist it was out for about 20 minutes and kept dry. No signs of head injury.",True,"A knocked-out permanent tooth has the best chance if replanted quickly. Keeping it moist and not touching the root protects the cells that help it reattach."],
   ["Scrub the tooth clean with a toothbrush before giving it to the dentist.",False,"Scrubbing destroys the root cells the tooth needs to reattach."],
   ["Wrap it back in a dry napkin and schedule an appointment for next week.",False,"Every minute counts. Dry storage kills the root cells."],
   ["It's a baby tooth, so throw it away.",False,"At age 9 a front tooth is usually permanent. Let the dentist decide; never throw it away."]]},
 'chartIt':[["Her tooth was knocked completely out.","Avulsion",["Avulsion","Luxation","Fracture","Abrasion"],"Avulsion means torn away. Luxation means displaced but still in the socket."],
            ["A cut inside her upper lip.","Laceration",["Laceration","Contusion","Abrasion","Ulcer"],"A laceration is a cut in the skin or soft tissue."],
            ["Her mouth was bleeding.","Hemorrhage",["Hemorrhage","Hematoma","Hematuria","Hemolysis"],"Hem/o (blood) + -rrhage (bursting forth): bleeding."]]},
]
