# MedDecode Sort: program decks (EMT, CNA, CCMA, Dental). Drafts for instructor review.
I = lambda t,k,c,n,say=None,also=None,alt=None: {k_:v for k_,v in dict(t=t,k=k,c=c,n=n,say=say,also=also,alt=alt).items() if v}
DECKS = {
'EMT': {'name':'EMT', 'bins':[
  dict(id='region', name='Body region', def_='A part or area of the body you assess or describe.', hint='Is it a place on or in the body?'),
  dict(id='finding', name='Assessment finding', def_='A sign or symptom you find during your assessment.', hint='Is it something you see, hear, feel or measure on the patient?'),
  dict(id='impression', name='Field impression', def_='The condition you suspect, based on your assessment.', hint='Is it the name of the problem you think the patient has?'),
  dict(id='moi', name='Mechanism of injury', def_='How the injury happened: the force or event.', hint='Does it describe how the patient got hurt?'),
  dict(id='tx', name='Intervention', def_='Care an EMT gives or equipment an EMT uses.', hint='Is it something you do or use to help the patient?')],
 'items':[
  I('cervical spine','phrase','region','The seven vertebrae of the neck. Protect it after any significant head or neck trauma.','SER-vih-kul spyn'),
  I('thorax','term','region','The chest: the area between the neck and the abdomen.','THOR-aks'),
  I('femur','term','region','The thigh bone, the longest bone in the body.','FEE-mur'),
  I('pelvis','term','region','The ring of bones at the base of the spine. A pelvic fracture can cause severe internal bleeding.','PEL-vis'),
  I('cranium','term','region','The skull, the bones that protect the brain.','KRAY-nee-um'),
  I('sternum','term','region','The breastbone. CPR compressions go on the lower half of the sternum.','STER-num'),
  I('right upper quadrant','phrase','region','The area of the abdomen that holds most of the liver and the gallbladder.'),
  I('trachea','term','region','The windpipe. Check that it is in the midline of the neck.','TRAY-kee-uh'),
  I('cyanosis','term','finding','cyan/o (blue) + -osis: bluish skin from too little oxygen.','sy-uh-NOH-sis'),
  I('tachypnea','term','finding','tachy- (fast) + -pnea (breathing): a fast breathing rate.','tak-ip-NEE-uh'),
  I('diaphoresis','term','finding','Heavy sweating. Pale, cool, sweaty skin is a warning sign of shock or a heart attack.','dy-uh-for-EE-sis'),
  I('bradycardia','term','finding','brady- (slow) + cardi (heart) + -ia: a heart rate under 60.','brad-ee-KAR-dee-uh'),
  I('dyspnea','term','finding','dys- (difficult) + -pnea (breathing): shortness of breath.','DISP-nee-uh'),
  I('crepitus','term','finding','A grating or crackling feel or sound, as when broken bone ends rub together.','KREP-ih-tus'),
  I('unequal pupils','phrase','finding','Pupils of different sizes can be a sign of a head injury or stroke.'),
  I('jugular vein distention','phrase','finding','Bulging neck veins, a sign of fluid backing up toward the heart (for example, heart failure or tension pneumothorax).'),
  I('anaphylaxis','term','impression','A severe, life-threatening allergic reaction affecting the airway, breathing or circulation.','an-uh-fih-LAK-sis'),
  I('hypoglycemia','term','impression','hypo- (below normal) + glyc (sugar) + -emia (blood condition): low blood sugar.','hy-poh-gly-SEE-mee-uh'),
  I('myocardial infarction','phrase','impression','A heart attack: death of heart muscle (my/o + cardi) when its blood supply is blocked.','my-oh-KAR-dee-ul in-FARK-shun'),
  I('cerebrovascular accident','phrase','impression','A stroke: blocked or bleeding blood vessels in the brain (cerebr/o + vascul/o).','seh-ree-broh-VAS-kyuh-ler AK-sih-dent'),
  I('hypothermia','term','impression','hypo- (below normal) + therm (heat) + -ia: a dangerously low body temperature.','hy-poh-THER-mee-uh'),
  I('pneumothorax','term','impression','Air (pneum/o) in the chest (thorax) outside the lung, causing it to collapse.','noo-moh-THOR-aks'),
  I('hypovolemic shock','phrase','impression','Shock caused by too little blood or fluid volume, often from bleeding.','hy-poh-voh-LEE-mik shok'),
  I('heat stroke','phrase','impression','A life-threatening rise in body temperature, with altered mental status.'),
  I('fall from height','phrase','moi','A mechanism of injury. Falls greater than 20 feet for adults are considered significant.'),
  I('motor vehicle collision','phrase','moi','A car crash (MVC). Note the damage, speed and restraint use.'),
  I('blunt trauma','phrase','moi','Injury from a force that does not break the skin, such as a punch or steering wheel.'),
  I('penetrating trauma','phrase','moi','Injury from an object that breaks the skin, such as a knife or bullet.'),
  I('rollover crash','phrase','moi','A vehicle that rolled over; a high-risk mechanism of injury.'),
  I('ejection from a vehicle','phrase','moi','Being thrown from a vehicle: one of the highest-risk mechanisms of injury.'),
  I('diving into shallow water','phrase','moi','A classic mechanism for a cervical spine injury.'),
  I('pedestrian struck by a vehicle','phrase','moi','A person on foot hit by a car; expect multiple injuries.'),
  I('nonrebreather mask','phrase','tx','A mask that delivers high-flow oxygen.'),
  I('cardiopulmonary resuscitation','phrase','tx','CPR: chest compressions and rescue breaths (cardi/o heart + pulmon/o lung).','kar-dee-oh-PUL-muh-nair-ee'),
  I('automated external defibrillator','phrase','tx','An AED: a device that shocks the heart out of a deadly rhythm.'),
  I('cervical collar','phrase','tx','A collar that limits neck movement after a possible spine injury.'),
  I('tourniquet','term','tx','A band tightened above a wound to stop life-threatening bleeding from an arm or leg.','TUR-nih-kit'),
  I('epinephrine auto-injector','phrase','tx','A pen that injects epinephrine for anaphylaxis (used per protocol).','ep-ih-NEF-rin'),
  I('oral glucose','phrase','tx','Sugar gel given by mouth for low blood sugar when the patient can swallow.'),
  I('bag-valve mask','phrase','tx','A hand-squeezed bag and mask used to breathe for a patient.'),
 ]},
'CNA': {'name':'CNA / Nursing', 'bins':[
  dict(id='body', name='Body part', def_='A part of the body you observe or care for.', hint='Is it a place on or in the body?'),
  dict(id='report', name='Observation to report', def_='A change or problem you tell the nurse about right away.', hint='Is it a change or problem the nurse needs to know about?'),
  dict(id='vital', name='Vital sign or measurement', def_='Something you measure and record.', hint='Is it a number you measure and write down?'),
  dict(id='adl', name='Care task (ADL)', def_='Daily care you help residents with: activities of daily living.', hint='Is it daily care you help a resident do?'),
  dict(id='safety', name='Safety and infection control', def_='Something that prevents falls, injuries or the spread of germs.', hint='Does it keep the resident or you safe from falls or germs?')],
 'items':[
  I('sacrum','term','body','The bone at the base of the spine. A common place for pressure injuries.','SAY-krum'),
  I('coccyx','term','body','The tailbone, at the very bottom of the spine.','KOK-siks'),
  I('perineum','term','body','The area between the legs, between the genitals and the anus. Clean it during perineal care.','pair-ih-NEE-um'),
  I('axilla','term','body','The armpit. One place to take a temperature.','ak-SIL-uh'),
  I('urinary bladder','phrase','body','The organ that stores urine (cyst/o).'),
  I('oral mucosa','phrase','body','The moist lining of the mouth. Check it during oral care.','OR-ul myoo-KOH-suh'),
  I('heels','term','body','A bony area where pressure injuries often form in residents who stay in bed.'),
  I('dysphagia','term','report','dys- (difficult) + phag (swallow) + -ia: coughing or choking with meals. Report it; the resident may need a diet change.','dis-FAY-jee-uh'),
  I('hematuria','term','report','hemat/o (blood) + -uria: blood in the urine.','hee-muh-TOO-ree-uh'),
  I('new confusion','phrase','report','A sudden change in mental status is never "just age." Report it right away.'),
  I('reddened area that does not fade','phrase','report','A possible stage 1 pressure injury. Report it and keep pressure off it.'),
  I('dyspnea','term','report','dys- + -pnea: shortness of breath.','DISP-nee-uh'),
  I('swollen ankles','phrase','report','Edema: fluid in the tissues. New or worse swelling should be reported.'),
  I('oliguria','term','report','olig/o (scanty) + -uria: very little urine output.','ol-ih-GYOO-ree-uh'),
  I('emesis','term','report','Vomiting. Note the amount, color and time.','EM-eh-sis'),
  I('blood pressure','phrase','vital','The force of blood against the artery walls, recorded as two numbers.'),
  I('pulse rate','phrase','vital','Heartbeats per minute, often counted at the radial artery in the wrist.'),
  I('respiratory rate','phrase','vital','Breaths per minute; count without telling the resident.'),
  I('temperature','term','vital','Body heat, measured by mouth, ear, forehead, armpit or rectum.'),
  I('oxygen saturation','phrase','vital','SpO2: the percentage of red blood cells carrying oxygen, measured with a pulse oximeter.'),
  I('intake and output','phrase','vital','I&O: measuring everything a resident drinks and every amount of urine or other output.'),
  I('daily weight','phrase','vital','Weighing at the same time, on the same scale, in similar clothing, to track fluid changes.'),
  I('pain level','phrase','vital','The resident\'s pain on a 0 to 10 scale, often called the fifth vital sign.'),
  I('perineal care','phrase','adl','Cleaning the perineum, front to back, to prevent infection.','pair-ih-NEE-ul'),
  I('oral care','phrase','adl','Brushing teeth, cleaning dentures and moistening the mouth.'),
  I('ambulation','term','adl','Walking with a resident, often with a gait belt.','am-byoo-LAY-shun'),
  I('feeding assistance','phrase','adl','Helping a resident eat safely, sitting upright, with small bites.'),
  I('bed bath','phrase','adl','Bathing a resident who cannot get out of bed.'),
  I('toileting','term','adl','Helping a resident use the toilet, commode, bedpan or urinal.'),
  I('range-of-motion exercises','phrase','adl','Moving joints through their full motion to prevent stiffness.'),
  I('denture care','phrase','adl','Cleaning and storing dentures safely in a labeled cup.'),
  I('hand hygiene','phrase','safety','Handwashing or hand sanitizer: the most important way to stop the spread of germs.'),
  I('gait belt','phrase','safety','A belt around the resident\'s waist that you hold to steady them while walking or transferring.'),
  I('standard precautions','phrase','safety','Treating all blood and body fluids as possibly infectious.'),
  I('personal protective equipment','phrase','safety','PPE: gloves, gowns, masks and eye protection.'),
  I('bed in the lowest position','phrase','safety','Keeping the bed low reduces injuries if a resident falls.'),
  I('call light within reach','phrase','safety','So the resident can ask for help instead of getting up alone.'),
  I('isolation precautions','phrase','safety','Extra steps, such as gowns and masks, for residents with certain infections.'),
  I('nonskid footwear','phrase','safety','Socks or shoes with grips that help prevent falls.'),
 ]},
'CCMA': {'name':'CCMA', 'bins':[
  dict(id='body', name='Body part', def_='An organ, tissue or area of the body.', hint='Is it a place on or in the body?'),
  dict(id='sx', name='Symptom (chief complaint)', def_='What the patient reports when they call or come in.', hint='Is it something the patient feels and tells you about?'),
  dict(id='dx', name='Diagnosis', def_='The condition the provider identifies.', hint='Is it the name of a disease or condition?'),
  dict(id='test', name='Lab test or screening', def_='A specimen test or screening the MA may collect or perform.', hint='Is it a test of a specimen or a screening?'),
  dict(id='proc', name='Clinical procedure', def_='A skill or procedure done in the clinic.', hint='Is it a hands-on skill done to the patient in the clinic?')],
 'items':[
  I('pharynx','term','body','The throat. A throat swab is taken from the back of the pharynx.','FAIR-inks'),
  I('tympanic membrane','phrase','body','The eardrum (tympan/o).','tim-PAN-ik MEM-brayn'),
  I('antecubital space','phrase','body','The inside of the elbow, the most common venipuncture site.','an-tee-KYOO-bih-tul'),
  I('deltoid muscle','phrase','body','The shoulder muscle, a common site for vaccines given intramuscularly.','DEL-toyd'),
  I('thyroid gland','phrase','body','The gland in the front of the neck that controls metabolism.','THY-royd'),
  I('larynx','term','body','The voice box (laryng/o).','LAIR-inks'),
  I('radial artery','phrase','body','The artery on the thumb side of the wrist where you count the pulse.','RAY-dee-ul'),
  I('otalgia','term','sx','ot/o (ear) + -algia (pain): an earache.','oh-TAL-juh'),
  I('dysuria','term','sx','dys- (painful) + -uria (urine): burning or pain with urination.','dis-YOO-ree-uh'),
  I('cephalalgia','term','sx','cephal/o (head) + -algia (pain): a headache.','sef-uh-LAL-juh'),
  I('nausea','term','sx','A feeling of needing to vomit.','NAW-zee-uh'),
  I('rhinorrhea','term','sx','rhin/o (nose) + -rrhea (discharge): a runny nose.','ry-noh-REE-uh'),
  I('arthralgia','term','sx','arthr/o (joint) + -algia (pain): joint pain.','ar-THRAL-jee-uh'),
  I('fatigue','term','sx','Tiredness that does not go away with rest.','fuh-TEEG'),
  I('pruritus','term','sx','Itching.','proo-RY-tus'),
  I('hypertension','term','dx','hyper- (above normal) + tension (pressure): high blood pressure.','hy-per-TEN-shun'),
  I('otitis media','phrase','dx','Inflammation (infection) of the middle ear (ot/o + -itis).','oh-TY-tis MEE-dee-uh'),
  I('type 2 diabetes mellitus','phrase','dx','A condition in which the body does not use insulin well, so blood sugar runs high.'),
  I('streptococcal pharyngitis','phrase','dx','Strep throat: a bacterial infection of the throat (pharyng/o + -itis).','strep-toh-KOK-ul fair-in-JY-tis'),
  I('urinary tract infection','phrase','dx','UTI: an infection anywhere in the urinary tract, most often the bladder.'),
  I('hypothyroidism','term','dx','hypo- + thyroid + -ism: an underactive thyroid gland.','hy-poh-THY-roy-diz-um'),
  I('gastroesophageal reflux disease','phrase','dx','GERD: stomach acid flowing back up into the esophagus.','gas-troh-eh-sof-uh-JEE-ul'),
  I('urinalysis','term','test','A lab test of a urine specimen for signs of infection, sugar, blood and more.','yoo-rih-NAL-ih-sis'),
  I('rapid strep test','phrase','test','A throat swab tested in the office for strep bacteria.'),
  I('hemoglobin A1c','phrase','test','A blood test showing average blood sugar over about three months.','HEE-moh-gloh-bin ay-wun-SEE'),
  I('complete blood count','phrase','test','CBC: counts the red cells, white cells and platelets in a blood sample.'),
  I('lipid panel','phrase','test','A blood test for cholesterol and triglycerides.'),
  I('urine pregnancy test','phrase','test','Detects the pregnancy hormone hCG in urine.'),
  I('mammogram','term','test','mamm/o (breast) + -gram (record): a screening x-ray of the breast.','MAM-oh-gram'),
  I('vision screening','phrase','test','Checking how well a patient sees, often with a Snellen eye chart.'),
  I('venipuncture','term','proc','Puncturing a vein (ven/i) to draw blood.','VEN-ih-punk-cher'),
  I('intramuscular injection','phrase','proc','IM: an injection into a muscle (intra- within + muscul/o).','in-truh-MUS-kyoo-ler'),
  I('electrocardiogram','term','proc','ECG or EKG: placing electrodes to record the heart\'s electrical activity.','ee-lek-troh-KAR-dee-oh-gram', also=['test'], alt='An ECG is a procedure the MA performs, and it is also a diagnostic test.'),
  I('ear irrigation','phrase','proc','Flushing the ear canal with warm water to remove wax.'),
  I('suture removal','phrase','proc','Removing stitches once a wound has healed.'),
  I('capillary puncture','phrase','proc','A finger stick to collect a small blood sample.'),
  I('sterile dressing change','phrase','proc','Replacing a wound covering using sterile technique.'),
  I('nebulizer treatment','phrase','proc','Giving inhaled medicine as a mist through a mask or mouthpiece.','NEB-yoo-ly-zer'),
 ]},
'Dental': {'name':'Dental', 'bins':[
  dict(id='anat', name='Tooth or mouth structure', def_='A part of a tooth or the mouth.', hint='Is it a part of a tooth, the gums or the jaw?'),
  dict(id='cond', name='Dental condition', def_='A disease or problem of the teeth, gums or mouth.', hint='Is it a disease or problem in the mouth?'),
  dict(id='proc', name='Dental procedure', def_='Treatment done by the dental team.', hint='Is it a treatment done in the chair?'),
  dict(id='instr', name='Instrument or equipment', def_='A tool or device used in the operatory.', hint='Is it a tool or a piece of equipment?'),
  dict(id='alert', name='Medical alert', def_='A health-history item that changes how the patient is treated.', hint='Is it something in the health history the dentist must know before treatment?')],
 'items':[
  I('enamel','term','anat','The hard outer layer of the crown of a tooth, the hardest substance in the body.','ih-NAM-ul'),
  I('dentin','term','anat','The layer under the enamel that makes up most of the tooth (dent/o).','DEN-tin'),
  I('pulp','term','anat','The soft center of the tooth, with nerves and blood vessels.'),
  I('gingiva','term','anat','The gums (gingiv/o).','JIN-jih-vuh'),
  I('periodontal ligament','phrase','anat','Fibers that hold the tooth root in its socket (peri- around + odont/o tooth).','pair-ee-oh-DON-tul'),
  I('mandible','term','anat','The lower jaw.','MAN-dih-bul'),
  I('maxilla','term','anat','The upper jaw.','mak-SIL-uh'),
  I('cementum','term','anat','The thin layer covering the tooth root.','seh-MEN-tum'),
  I('dental caries','phrase','cond','Tooth decay: cavities.','KAIR-eez'),
  I('gingivitis','term','cond','gingiv/o (gums) + -itis: inflamed, bleeding gums.','jin-jih-VY-tis'),
  I('periodontitis','term','cond','peri- + odont/o + -itis: advanced gum disease with bone loss around the teeth.','pair-ee-oh-don-TY-tis'),
  I('abscess','term','cond','A pocket of pus from infection, at the tip of a root or in the gums.','AB-ses'),
  I('malocclusion','term','cond','A bad bite: the upper and lower teeth do not meet correctly.','mal-oh-KLOO-zhun'),
  I('xerostomia','term','cond','xer/o (dry) + stomat/o (mouth) + -ia: dry mouth, often a medicine side effect.','zeer-oh-STOH-mee-uh'),
  I('stomatitis','term','cond','stomat/o (mouth) + -itis: inflammation of the mouth.','stoh-muh-TY-tis'),
  I('bruxism','term','cond','Grinding or clenching the teeth, often during sleep.','BRUK-siz-um'),
  I('tooth avulsion','phrase','cond','A tooth knocked completely out of its socket: a dental emergency.','uh-VUL-shun'),
  I('prophylaxis','term','proc','A professional cleaning to prevent disease ("prophy").','proh-fih-LAK-sis'),
  I('root canal therapy','phrase','proc','Removing infected pulp from inside the tooth and sealing it (endodontics).'),
  I('extraction','term','proc','Removing a tooth.','ek-STRAK-shun'),
  I('scaling and root planing','phrase','proc','A deep cleaning below the gumline to treat periodontitis.'),
  I('sealant placement','phrase','proc','Painting a protective coating on the chewing surfaces of back teeth.'),
  I('composite restoration','phrase','proc','A tooth-colored filling.','kum-POZ-it'),
  I('fluoride varnish','phrase','proc','A fluoride coating painted on teeth to prevent decay.','FLOR-ide'),
  I('gingivectomy','term','proc','gingiv/o + -ectomy: surgical removal of gum tissue.','jin-jih-VEK-tuh-mee'),
  I('explorer','term','instr','A thin, pointed instrument used to feel tooth surfaces for decay.'),
  I('mouth mirror','phrase','instr','A small mirror for seeing hard-to-view areas and moving the cheek or tongue.'),
  I('periodontal probe','phrase','instr','A marked instrument that measures the depth of gum pockets in millimeters.'),
  I('high-volume evacuator','phrase','instr','HVE: strong suction that removes water and debris during treatment.'),
  I('saliva ejector','phrase','instr','A small, low-power suction tube that removes saliva.'),
  I('curette','term','instr','A spoon-shaped instrument used to scrape deposits from teeth and roots.','kyoo-RET'),
  I('handpiece','term','instr','The dental drill.'),
  I('autoclave','term','instr','A machine that sterilizes instruments with steam under pressure.','AW-toh-klayv'),
  I('anticoagulant','term','alert','A blood thinner. The patient may bleed more during extractions or deep cleanings.','an-tee-koh-AG-yoo-lunt'),
  I('latex allergy','phrase','alert','Use non-latex gloves, dams and supplies.'),
  I('penicillin allergy','phrase','alert','The dentist must choose a different antibiotic.'),
  I('artificial heart valve','phrase','alert','The patient may need antibiotics before some procedures, as the dentist directs.'),
  I('uncontrolled hypertension','phrase','alert','Very high blood pressure may mean delaying treatment. Take a reading before starting.'),
  I('diabetes mellitus','phrase','alert','Risk of low blood sugar in the chair and slower healing; ask when the patient last ate.'),
  I('bisphosphonate use','phrase','alert','Bone medicine that raises the risk of jawbone problems after extractions.','bis-FOS-foh-nayt'),
  I('pregnancy','term','alert','May change the timing of x-rays, medicines and elective treatment.'),
 ]},
}
